/**
 * Optionnel : associer un type de fond à une image de joueur.
 * Clé = chemin image (ex. assets/collection/mbappe-99.png)
 * Valeur = un des types : 'noir-or', 'bleu-cosmos', 'magenta-tots', 'blanc-cristal', 'or-texture', 'violet'
 * Si une image n'est pas dans ce tableau, le rangement utilise un ordre par défaut (répartition automatique).
 */
window.FONDS_PAR_IMAGE = {
  // Catégorie Magenta (fond magenta / TOTS)
  'assets/collection/mbappe-99.png': 'magenta-tots',
  'assets/collection/messi-99.png': 'magenta-tots',
  'assets/collection/haaland-98.png': 'magenta-tots',
  'assets/collection/lewandowski-99.png': 'magenta-tots',
  'assets/collection/de-paul-99.png': 'magenta-tots',
  'assets/collection/salah-99.png': 'magenta-tots',
  'assets/collection/musiala-98.png': 'magenta-tots',
  'assets/collection/vinicius-98.png': 'magenta-tots',
  'assets/collection/courtois-98.png': 'magenta-tots',
  'assets/collection/davies-97.png': 'magenta-tots',
  'assets/collection/davies-97-gold.png': 'magenta-tots',
  'assets/collection/pedri-97.png': 'magenta-tots',
  'assets/collection/rodri-93.png': 'magenta-tots',

  // Catégorie Bleu cosmos
  'assets/collection/hakimi-94.png': 'bleu-cosmos',
  'assets/collection/mbappe-96.png': 'bleu-cosmos',
  'assets/collection/vini-jr-95.png': 'bleu-cosmos',
  'assets/collection/courtois-92.png': 'bleu-cosmos',
  'assets/collection/de-bruyne-96.png': 'bleu-cosmos',
  'assets/collection/bellingham-96.png': 'bleu-cosmos',
  'assets/collection/lewandowski-97.png': 'bleu-cosmos',
  'assets/collection/rodri-97.png': 'bleu-cosmos',
  'assets/collection/pedri-95.png': 'bleu-cosmos',
  'assets/collection/ruben-dias.png': 'bleu-cosmos',
  'assets/collection/rodri-95.png': 'bleu-cosmos',

  // Catégorie Blanc cristal
  'assets/collection/henry.png': 'blanc-cristal',
  'assets/collection/pele.png': 'blanc-cristal',
  'assets/collection/maradona.png': 'blanc-cristal',
  'assets/collection/zidane.png': 'blanc-cristal',
  'assets/collection/ronaldinho.png': 'blanc-cristal',
  'assets/collection/ronaldo-icon.png': 'blanc-cristal',
  'assets/collection/henry-icon.png': 'blanc-cristal',
  'assets/collection/cruyff.png': 'blanc-cristal',
  'assets/collection/maldini.png': 'blanc-cristal',
  'assets/collection/roberto-carlos.png': 'blanc-cristal',
  'assets/collection/gullit.png': 'blanc-cristal',
  'assets/collection/puskas.png': 'blanc-cristal',
  'assets/collection/yashin.png': 'blanc-cristal',
  'assets/collection/kaka.png': 'blanc-cristal',
  'assets/collection/cantona.png': 'blanc-cristal',
  'assets/collection/del-piero.png': 'blanc-cristal',
  'assets/collection/pirlo.png': 'blanc-cristal',
  'assets/collection/drogba.png': 'blanc-cristal',

  // Catégorie Or texture
  'assets/collection/zaire-emery.png': 'or-texture',
  'assets/collection/joao-felix.png': 'or-texture',
  'assets/collection/ricardo-horta.png': 'or-texture',
  'assets/collection/camavinga.png': 'or-texture',
  'assets/pack25/romero.png': 'or-texture',
  'assets/pack25/laporte.png': 'or-texture',
  'assets/pack25/gakpo.png': 'or-texture',
  'assets/pack25/kolo-muani.png': 'or-texture',
  'assets/pack25/diaby.png': 'or-texture',
  'assets/pack25/ziyech.png': 'or-texture',
  'assets/pack30/gnabry.png': 'or-texture',
  'assets/pack30/gvardiol.png': 'or-texture',
  'assets/pack30/joao-cancelo.png': 'or-texture',
  'assets/pack30/szczesny.png': 'or-texture',
  'assets/pack30/fernandez.png': 'or-texture',
  'assets/pack55/ronaldo.png': 'or-texture',
  'assets/pack25/foden.png': 'or-texture',
  'assets/pack25/depay.png': 'or-texture',
  'assets/pack25/carvajal.png': 'or-texture',
  'assets/pack25/hernandez.png': 'or-texture',
  'assets/pack30/rashford.png': 'or-texture',
  'assets/pack30/bruno-guimaraes.png': 'or-texture',
  'assets/pack30/ter-stegen.png': 'or-texture',
  'assets/pack45/varane.png': 'or-texture',
  'assets/pack45/robertson.png': 'or-texture',
  'assets/pack45/mahrez.png': 'or-texture',
  'assets/pack45/neuer.png': 'or-texture',
  'assets/pack55/messi.png': 'or-texture',
  'assets/collection/rudiger.png': 'or-texture',
  'assets/collection/kvaratskhelia.png': 'or-texture',
  'assets/pack30/odegaard.png': 'or-texture',
  'assets/pack30/dybala.png': 'or-texture',
  'assets/pack45/ter-stegen.png': 'or-texture',
  'assets/pack45/bruno-fernandes.png': 'or-texture',
  'assets/pack45/son.png': 'or-texture',
  'assets/pack45/martinez.png': 'or-texture',
  'assets/pack45/alisson.png': 'or-texture',
  'assets/pack50/valverde.png': 'or-texture',
  'assets/pack50/lewandowski.png': 'or-texture',
  'assets/pack50/griezmann.png': 'or-texture',
  'assets/pack50/hakimi.png': 'or-texture',
  'assets/pack50/donnarumma.png': 'or-texture',
  'assets/pack50/pedri.png': 'or-texture',
  'assets/pack50/casemiro.png': 'or-texture',
  'assets/pack50/kimmich.png': 'or-texture',
  'assets/pack50/rodri.png': 'or-texture',
  'assets/pack75/vini-jr.png': 'or-texture',
  'assets/pack75/van-dijk.png': 'or-texture',
  'assets/pack75/son.png': 'or-texture',
  'assets/pack75/haaland.png': 'or-texture',
  'assets/pack75/mbappe.png': 'or-texture',
  'assets/collection/hernandez-81.png': 'or-texture',

  // Catégorie Noir & Or géométrique
  'assets/futgraphics/Carlos_Espí_Team of the Week.png': 'noir-or',
  'assets/futgraphics/Chibuike_Nwaiwu_Team of the Week.png': 'noir-or',
  'assets/futgraphics/Daniel_Munie_Team of the Week.png': 'noir-or',
  'assets/futgraphics/David_McGoldrick_Team of the Week.png': 'noir-or',
  'assets/futgraphics/Farès_Chaïbi_Team of the Week.png': 'noir-or',
  'assets/futgraphics/Iago_Aspas_Team of the Week.png': 'noir-or',
  'assets/futgraphics/Igor_Paixão_Team of the Week.png': 'noir-or',
  'assets/futgraphics/Iñigo_Martínez_Team of the Week.png': 'noir-or',
  'assets/futgraphics/Jack_Payne_Team of the Week.png': 'noir-or',
  'assets/futgraphics/Jesús_Rodríguez_Team of the Week.png': 'noir-or',
  'assets/futgraphics/Joshua_Kimmich_Team of the Week.png': 'noir-or',
  'assets/futgraphics/Jurriën_Timber_Team of the Week.png': 'noir-or',
  'assets/futgraphics/Kristian_Thorstvedt_Team of the Week.png': 'noir-or',
  'assets/futgraphics/Lionel_Messi_Team of the Week.png': 'noir-or',
  'assets/futgraphics/Marshall_Munetsi_Team of the Week.png': 'noir-or',
  'assets/futgraphics/Martín_Satriano_Team of the Week.png': 'noir-or',
  'assets/futgraphics/Michael_Duffy_Team of the Week.png': 'noir-or',
  'assets/futgraphics/Mikkel_Damsgaard_Team of the Week.png': 'noir-or',
  'assets/futgraphics/Mohamed_Ihattaren_Team of the Week.png': 'noir-or',
  'assets/futgraphics/Nathan_Ngoy_Team of the Week.png': 'noir-or',
  'assets/futgraphics/Nikola_Vasilj_Team of the Week.png': 'noir-or',
  'assets/futgraphics/Rafael_Profini_Team of the Week.png': 'noir-or',
  'assets/futgraphics/Rani_Khedira_Team of the Week.png': 'noir-or',
  'assets/futgraphics/Rodrigo_Zalazar_Team of the Week.png': 'noir-or',
  'assets/futgraphics/Romelu_Lukaku_Team of the Week.png': 'noir-or',
  'assets/futgraphics/Thorgan_Hazard_Team of the Week.png': 'noir-or',
  'assets/futgraphics/Tristan_Crama_Team of the Week.png': 'noir-or',
  'assets/futgraphics/William_Gomes_Team of the Week.png': 'noir-or',
  'assets/collection/odegaard-88.png': 'noir-or',
  'assets/futgraphics/Aral_Şimşir_Team of the Week.png': 'noir-or',
  'assets/futgraphics/Bryan_Cristante_Team of the Week.png': 'noir-or',
  'assets/collection/schlotterbeck.png': 'noir-or',
  'assets/collection/salah-92.png': 'noir-or',
  'assets/collection/leao.png': 'noir-or',
  'assets/collection/osimhen.png': 'noir-or',
  'assets/collection/rice.png': 'noir-or',
  'assets/collection/bruno-fernandes-88.png': 'noir-or',
  'assets/collection/valverde-90.png': 'noir-or',

  // Catégorie Violet
  'assets/futgraphics/Adama_Traoré_Fantasy UT.png': 'violet',
  'assets/futgraphics/Amad_Special Item.png': 'violet',
  'assets/futgraphics/Andrej_Kramarić_Fantasy UT.png': 'violet',
  'assets/futgraphics/Arda_Güler_Fantasy UT.png': 'violet',
  'assets/futgraphics/Álex_Jiménez_Special Item.png': 'violet',
  'assets/futgraphics/Brenden_Aaronson_Special Item.png': 'violet',
  'assets/futgraphics/Conor_Gallagher_Fantasy UT.png': 'violet',
  'assets/futgraphics/Enzo_Millot_Fantasy UT.png': 'violet',
  'assets/futgraphics/Florian_Wirtz_Fantasy UT.png': 'violet',
  'assets/futgraphics/Estefanía_Banini_Fantasy UT.png': 'violet',
  'assets/futgraphics/Ethan_Nwaneri_Fantasy UT.png': 'violet',
  'assets/collection/nwaneri.png': 'autre',
  'assets/futgraphics/Félix_Correia_Fantasy UT.png': 'violet',
  'assets/futgraphics/Gonçalo_Guedes_Fantasy UT.png': 'violet',
  'assets/futgraphics/Kiernan_Dewsbury-Hall_Special Item.png': 'violet',
  'assets/futgraphics/Martin_Baturina_Fantasy UT.png': 'violet',
  'assets/futgraphics/Matheus_Nunes_Special Item.png': 'violet',
  'assets/futgraphics/Leandro_Trossard_Special Item.png': 'violet',
  'assets/futgraphics/Lewis_Miley_Fantasy UT.png': 'violet',
  'assets/futgraphics/Matteo_Ruggeri_Fantasy UT.png': 'violet',
  'assets/futgraphics/Mattéo_Guendouzi_Fantasy UT (1).png': 'violet',
  'assets/futgraphics/Mattéo_Guendouzi_Fantasy UT.png': 'violet',
  'assets/futgraphics/Mika_Godts_Fantasy UT.png': 'violet',
  'assets/futgraphics/Milos_Kerkez_Special Item.png': 'violet',
  'assets/futgraphics/Niclas_Füllkrug_Fantasy UT.png': 'violet',
  'assets/futgraphics/Odsonne_Edouard_Fantasy UT.png': 'violet',
  'assets/futgraphics/Oscar_Bobb_Fantasy UT.png': 'violet',
  'assets/futgraphics/Paul_Onuachu_Fantasy UT.png': 'violet',
  'assets/futgraphics/Pierre_Kalulu_Fantasy UT.png': 'violet',
  'assets/futgraphics/Raheem_Sterling_Fantasy UT.png': 'violet',
  'assets/futgraphics/Raúl_Jiménez_Special Item.png': 'violet',
  'assets/futgraphics/Robert_Sánchez_Special Item.png': 'violet',
  'assets/futgraphics/Sam_Coffey_Fantasy UT.png': 'violet',
  'assets/futgraphics/Sepp_van_den_Berg_Fantasy UT.png': 'violet',
  'assets/futgraphics/Tijjani_Reijnders_Fantasy UT.png': 'violet',
  'assets/futgraphics/Vangelis_Pavlidis_Fantasy UT.png': 'violet',
  'assets/collection/bruno-fernandes-93.png': 'violet',
  'assets/collection/joao-cancelo-90.png': 'violet',

  // Catégorie Autre
  'assets/futgraphics/Federico_Valverde_STAR PERFORMER.png': 'autre',
  'assets/futgraphics/Harry_Kewell_Fantasy UT Hero.png': 'autre',
  'assets/futgraphics/Iván_Zamorano_Fantasy UT Hero.png': 'autre',
  'assets/futgraphics/Mathys_Tel_Special Item.png': 'autre',
  'assets/futgraphics/Park_Ji_Sung_Fantasy UT Hero.png': 'autre',
  'assets/futgraphics/Tim_Cahill_Fantasy UT Hero.png': 'autre',
  'assets/futgraphics/Warren_Zaïre-Emery_Fantasy UT.png': 'autre',
  'assets/collection/gervinho.png': 'autre',
  'assets/collection/pedro-neto.png': 'autre',
  'assets/collection/nuno-mendes.png': 'autre',
  'assets/collection/tchouameni.png': 'autre',
  'assets/collection/kane-94.png': 'autre',
  'assets/collection/kane-90.png': 'autre',
  'assets/pack75/kane.png': 'autre',
  'assets/collection/musiala.png': 'autre',
  'assets/collection/musiala-98.png': 'autre',
  'assets/collection/musiala-88.png': 'autre',
  'assets/collection/hernandez-96.png': 'autre',
  'assets/futgraphics/Hidetoshi_Nakata_Fantasy UT Hero.png': 'autre',
  'assets/futgraphics/John_Arne_Riise_Fantasy UT Hero.png': 'autre',
  'assets/futgraphics/Pablo_Aimar_Fantasy UT Hero.png': 'autre',
  'assets/futgraphics/Alexander_Sørloth_STAR PERFORMER.png': 'autre',
  'assets/futgraphics/Barış_Alper_Yılmaz_STAR PERFORMER.png': 'autre',
  'assets/futgraphics/Davide_Zappacosta_STAR PERFORMER.png': 'autre',
  'assets/futgraphics/Georges_Mikautadze_POTM LALIGA EA SPORTS.png': 'autre',
  'assets/futgraphics/Rafael_Márquez_Fantasy UT Hero.png': 'autre',
  'assets/futgraphics/Wesley_Sneijder_Fantasy UT Hero.png': 'autre',
  'assets/futgraphics/Wifi_POTM LIGA F.png': 'autre',

  'assets/futgraphics/Warren_Zaïre-Emery_Fantasy UT.png': 'violet',
  'assets/futgraphics/Mathys_Tel_Special Item.png': 'violet'
};
