/**
 * Liste de tous les joueurs (packs 25k, 30k, 45k, 50k, 55k spécial, 75k + Ronaldo & Messi pour pack 55k).
 * Chaque joueur : { name, ovr, image }
 */
var JOUEURS_COLLECTION = [
  { name: 'Romero', ovr: 82, image: 'assets/pack25/romero.png' },
  { name: 'Laporte', ovr: 82, image: 'assets/pack25/laporte.png' },
  { name: 'Gnabry', ovr: 82, image: 'assets/pack30/gnabry.png' },
  { name: 'Gakpo', ovr: 83, image: 'assets/pack25/gakpo.png' },
  { name: 'Kolo Muani', ovr: 84, image: 'assets/pack25/kolo-muani.png' },
  { name: 'Diaby', ovr: 84, image: 'assets/pack25/diaby.png' },
  { name: 'Ziyech', ovr: 84, image: 'assets/pack25/ziyech.png' },
  { name: 'Gvardiol', ovr: 84, image: 'assets/pack30/gvardiol.png' },
  { name: 'João Cancelo', ovr: 84, image: 'assets/pack30/joao-cancelo.png' },
  { name: 'Szczęsny', ovr: 84, image: 'assets/pack30/szczesny.png' },
  { name: 'Fernández', ovr: 84, image: 'assets/pack30/fernandez.png' },
  { name: 'Hernández', ovr: 85, image: 'assets/pack25/hernandez.png' },
  { name: 'Foden', ovr: 85, image: 'assets/pack25/foden.png' },
  { name: 'Depay', ovr: 85, image: 'assets/pack25/depay.png' },
  { name: 'Carvajal', ovr: 85, image: 'assets/pack25/carvajal.png' },
  { name: 'Rashford', ovr: 85, image: 'assets/pack30/rashford.png' },
  { name: 'Varane', ovr: 85, image: 'assets/pack45/varane.png' },
  { name: 'Cristiano Ronaldo', ovr: 85, image: 'assets/pack55/ronaldo.png' },
  { name: 'Bruno Guimarães', ovr: 86, image: 'assets/pack30/bruno-guimaraes.png' },
  { name: 'ter Stegen', ovr: 86, image: 'assets/pack30/ter-stegen.png' },
  { name: 'Robertson', ovr: 86, image: 'assets/pack45/robertson.png' },
  { name: 'Mahrez', ovr: 86, image: 'assets/pack45/mahrez.png' },
  { name: 'Messi', ovr: 86, image: 'assets/pack55/messi.png' },
  { name: 'Ødegaard', ovr: 87, image: 'assets/pack30/odegaard.png' },
  { name: 'Dybala', ovr: 87, image: 'assets/pack30/dybala.png' },
  { name: 'Son', ovr: 87, image: 'assets/pack45/son.png' },
  { name: 'Bruno Fernandes', ovr: 87, image: 'assets/pack45/bruno-fernandes.png' },
  { name: 'Neuer', ovr: 87, image: 'assets/pack45/neuer.png' },
  { name: 'ter Stegen', ovr: 88, image: 'assets/pack45/ter-stegen.png' },
  { name: 'Martínez', ovr: 88, image: 'assets/pack45/martinez.png' },
  { name: 'Lewandowski', ovr: 88, image: 'assets/pack50/lewandowski.png' },
  { name: 'Griezmann', ovr: 88, image: 'assets/pack50/griezmann.png' },
  { name: 'Hakimi', ovr: 89, image: 'assets/pack50/hakimi.png' },
  { name: 'Valverde', ovr: 89, image: 'assets/pack50/valverde.png' },
  { name: 'Donnarumma', ovr: 89, image: 'assets/pack50/donnarumma.png' },
  { name: 'Pedri', ovr: 89, image: 'assets/pack50/pedri.png' },
  { name: 'Casemiro', ovr: 89, image: 'assets/pack50/casemiro.png' },
  { name: 'Kimmich', ovr: 89, image: 'assets/pack50/kimmich.png' },
  { name: 'Vini Jr', ovr: 89, image: 'assets/pack75/vini-jr.png' },
  { name: 'van Dijk', ovr: 89, image: 'assets/pack75/van-dijk.png' },
  { name: 'Son', ovr: 89, image: 'assets/pack75/son.png' },
  { name: 'Rodri', ovr: 90, image: 'assets/pack50/rodri.png' },
  { name: 'Haaland', ovr: 90, image: 'assets/pack75/haaland.png' },
  { name: 'Kane', ovr: 90, image: 'assets/pack75/kane.png' },
  { name: 'Mbappé', ovr: 91, image: 'assets/pack75/mbappe.png' },
  { name: 'Bruno Fernandes', ovr: 93, image: 'assets/collection/bruno-fernandes-93.png' },
  { name: 'Henry', ovr: 86, image: 'assets/collection/henry.png' },
  { name: 'Gervinho', ovr: 90, image: 'assets/collection/gervinho.png' },
  { name: 'João Cancelo', ovr: 90, image: 'assets/collection/joao-cancelo-90.png' },
  { name: 'João Félix', ovr: 79, image: 'assets/collection/joao-felix.png' },
  { name: 'Nwaneri', ovr: 85, image: 'assets/collection/nwaneri.png' },
  { name: 'Pedro Neto', ovr: 89, image: 'assets/collection/pedro-neto.png' },
  { name: 'Ricardo Horta', ovr: 81, image: 'assets/collection/ricardo-horta.png' },
  { name: 'Schlotterbeck', ovr: 87, image: 'assets/collection/schlotterbeck.png' },
  { name: 'Nuno Mendes', ovr: 95, image: 'assets/collection/nuno-mendes.png' },
  { name: 'Kvaratskhelia', ovr: 87, image: 'assets/collection/kvaratskhelia.png' },
  { name: 'Hakimi', ovr: 94, image: 'assets/collection/hakimi-94.png' },
  { name: 'Zaïre-Emery', ovr: 80, image: 'assets/collection/zaire-emery.png' },
  { name: 'Barcola', ovr: 92, image: 'assets/collection/barcola.png' },
  { name: 'Hernández', ovr: 81, image: 'assets/collection/hernandez-81.png' },
  { name: 'Mbappé', ovr: 96, image: 'assets/collection/mbappe-96.png' },
  { name: 'Vini Jr', ovr: 95, image: 'assets/collection/vini-jr-95.png' },
  { name: 'Courtois', ovr: 92, image: 'assets/collection/courtois-92.png' },
  { name: 'Rüdiger', ovr: 86, image: 'assets/collection/rudiger.png' },
  { name: 'Camavinga', ovr: 83, image: 'assets/collection/camavinga.png' },
  { name: 'Tchouaméni', ovr: 94, image: 'assets/collection/tchouameni.png' },
  { name: 'De Bruyne', ovr: 96, image: 'assets/collection/de-bruyne-96.png' },
  { name: 'Bellingham', ovr: 96, image: 'assets/collection/bellingham-96.png' },
  { name: 'Lewandowski', ovr: 97, image: 'assets/collection/lewandowski-97.png' },
  { name: 'Rodri', ovr: 97, image: 'assets/collection/rodri-97.png' },
  { name: 'Pedri', ovr: 95, image: 'assets/collection/pedri-95.png' },
  { name: 'Kane', ovr: 94, image: 'assets/collection/kane-94.png' },
  { name: 'Musiala', ovr: 90, image: 'assets/collection/musiala.png' },
  { name: 'Pelé', ovr: 95, image: 'assets/collection/pele.png' },
  { name: 'Maradona', ovr: 95, image: 'assets/collection/maradona.png' },
  { name: 'Zidane', ovr: 94, image: 'assets/collection/zidane.png' },
  { name: 'Ronaldinho', ovr: 93, image: 'assets/collection/ronaldinho.png' },
  { name: 'Ronaldo', ovr: 94, image: 'assets/collection/ronaldo-icon.png' },
  { name: 'Henry', ovr: 91, image: 'assets/collection/henry-icon.png' },
  { name: 'Cruyff', ovr: 93, image: 'assets/collection/cruyff.png' },
  { name: 'Maldini', ovr: 92, image: 'assets/collection/maldini.png' },
  { name: 'Roberto Carlos', ovr: 90, image: 'assets/collection/roberto-carlos.png' },
  { name: 'Gullit', ovr: 90, image: 'assets/collection/gullit.png' },
  { name: 'Puskás', ovr: 92, image: 'assets/collection/puskas.png' },
  { name: 'Yashin', ovr: 92, image: 'assets/collection/yashin.png' },
  { name: 'Kaká', ovr: 89, image: 'assets/collection/kaka.png' },
  { name: 'Cantona', ovr: 89, image: 'assets/collection/cantona.png' },
  { name: 'Del Piero', ovr: 90, image: 'assets/collection/del-piero.png' },
  { name: 'Pirlo', ovr: 90, image: 'assets/collection/pirlo.png' },
  { name: 'Drogba', ovr: 89, image: 'assets/collection/drogba.png' },
  { name: 'Mbappé', ovr: 99, image: 'assets/collection/mbappe-99.png' },
  { name: 'Haaland', ovr: 98, image: 'assets/collection/haaland-98.png' },
  { name: 'Messi', ovr: 99, image: 'assets/collection/messi-99.png' },
  { name: 'Vini Jr', ovr: 98, image: 'assets/collection/vinicius-98.png' },
  { name: 'Salah', ovr: 99, image: 'assets/collection/salah-99.png' },
  { name: 'Lewandowski', ovr: 99, image: 'assets/collection/lewandowski-99.png' },
  { name: 'De Paul', ovr: 99, image: 'assets/collection/de-paul-99.png' },
  { name: 'Rodri', ovr: 93, image: 'assets/collection/rodri-93.png' },
  { name: 'Davies', ovr: 97, image: 'assets/collection/davies-97.png' },
  { name: 'Pedri', ovr: 97, image: 'assets/collection/pedri-97.png' },
  { name: 'Musiala', ovr: 98, image: 'assets/collection/musiala-98.png' },
  { name: 'Courtois', ovr: 98, image: 'assets/collection/courtois-98.png' },
  { name: 'Hernández', ovr: 96, image: 'assets/collection/hernandez-96.png' },
  { name: 'Salah', ovr: 92, image: 'assets/collection/salah-92.png' },
  { name: 'Leão', ovr: 89, image: 'assets/collection/leao.png' },
  { name: 'Osimhen', ovr: 89, image: 'assets/collection/osimhen.png' },
  { name: 'Ødegaard', ovr: 88, image: 'assets/collection/odegaard-88.png' },
  { name: 'Rice', ovr: 89, image: 'assets/collection/rice.png' },
  { name: 'Bruno Fernandes', ovr: 88, image: 'assets/collection/bruno-fernandes-88.png' },
  { name: 'Davies', ovr: 97, image: 'assets/collection/davies-97-gold.png' },
  { name: 'Rúben Dias', ovr: 97, image: 'assets/collection/ruben-dias.png' },
  { name: 'Rodri', ovr: 95, image: 'assets/collection/rodri-95.png' },
  { name: 'Kane', ovr: 90, image: 'assets/collection/kane-90.png' },
  { name: 'Valverde', ovr: 90, image: 'assets/collection/valverde-90.png' },
  { name: 'Musiala', ovr: 88, image: 'assets/collection/musiala-88.png' }
];

/**
 * Joueurs FC26 depuis FutGraphics (https://futgraphics.com/database).
 * Dépose les images dans assets/futgraphics/ puis ajoute une ligne par joueur :
 * { name: 'Nom', ovr: XX, image: 'assets/futgraphics/nom-fichier.png' },
 */
var JOUEURS_FUTGRAPHICS_FC26 = [
  { name: 'Adama Traoré', ovr: 87, image: 'assets/futgraphics/Adama_Traoré_Fantasy UT.png' },
  { name: 'Alexander Sørloth', ovr: 91, image: 'assets/futgraphics/Alexander_Sørloth_STAR PERFORMER.png' },
  { name: 'Amad', ovr: 87, image: 'assets/futgraphics/Amad_Special Item.png' },
  { name: 'Andrej Kramarić', ovr: 87, image: 'assets/futgraphics/Andrej_Kramarić_Fantasy UT.png' },
  { name: 'Aral Şimşir', ovr: 85, image: 'assets/futgraphics/Aral_Şimşir_Team of the Week.png' },
  { name: 'Arda Güler', ovr: 87, image: 'assets/futgraphics/Arda_Güler_Fantasy UT.png' },
  { name: 'Álex Jiménez', ovr: 87, image: 'assets/futgraphics/Álex_Jiménez_Special Item.png' },
  { name: 'Barış Alper Yılmaz', ovr: 91, image: 'assets/futgraphics/Barış_Alper_Yılmaz_STAR PERFORMER.png' },
  { name: 'Brenden Aaronson', ovr: 87, image: 'assets/futgraphics/Brenden_Aaronson_Special Item.png' },
  { name: 'Bryan Cristante', ovr: 85, image: 'assets/futgraphics/Bryan_Cristante_Team of the Week.png' },
  { name: 'Carlos Espí', ovr: 85, image: 'assets/futgraphics/Carlos_Espí_Team of the Week.png' },
  { name: 'Chibuike Nwaiwu', ovr: 85, image: 'assets/futgraphics/Chibuike_Nwaiwu_Team of the Week.png' },
  { name: 'Conor Gallagher', ovr: 87, image: 'assets/futgraphics/Conor_Gallagher_Fantasy UT.png' },
  { name: 'Daniel Munie', ovr: 85, image: 'assets/futgraphics/Daniel_Munie_Team of the Week.png' },
  { name: 'David McGoldrick', ovr: 85, image: 'assets/futgraphics/David_McGoldrick_Team of the Week.png' },
  { name: 'Davide Zappacosta', ovr: 91, image: 'assets/futgraphics/Davide_Zappacosta_STAR PERFORMER.png' },
  { name: 'Diego Forlán', ovr: 91, image: 'assets/futgraphics/Diego_Forlán_Fantasy UT Hero.png' },
  { name: 'Enzo Millot', ovr: 87, image: 'assets/futgraphics/Enzo_Millot_Fantasy UT.png' },
  { name: 'Estefanía Banini', ovr: 87, image: 'assets/futgraphics/Estefanía_Banini_Fantasy UT.png' },
  { name: 'Ethan Nwaneri', ovr: 87, image: 'assets/futgraphics/Ethan_Nwaneri_Fantasy UT.png' },
  { name: 'Farès Chaïbi', ovr: 85, image: 'assets/futgraphics/Farès_Chaïbi_Team of the Week.png' },
  { name: 'Federico Valverde', ovr: 91, image: 'assets/futgraphics/Federico_Valverde_STAR PERFORMER.png' },
  { name: 'Félix Correia', ovr: 87, image: 'assets/futgraphics/Félix_Correia_Fantasy UT.png' },
  { name: 'Florian Wirtz', ovr: 87, image: 'assets/futgraphics/Florian_Wirtz_Fantasy UT.png' },
  { name: 'Georges Mikautadze', ovr: 88, image: 'assets/futgraphics/Georges_Mikautadze_POTM LALIGA EA SPORTS.png' },
  { name: 'Gonçalo Guedes', ovr: 87, image: 'assets/futgraphics/Gonçalo_Guedes_Fantasy UT.png' },
  { name: 'Harry Kewell', ovr: 91, image: 'assets/futgraphics/Harry_Kewell_Fantasy UT Hero.png' },
  { name: 'Hidetoshi Nakata', ovr: 91, image: 'assets/futgraphics/Hidetoshi_Nakata_Fantasy UT Hero.png' },
  { name: 'Iago Aspas', ovr: 85, image: 'assets/futgraphics/Iago_Aspas_Team of the Week.png' },
  { name: 'Igor Paixão', ovr: 85, image: 'assets/futgraphics/Igor_Paixão_Team of the Week.png' },
  { name: 'Iñigo Martínez', ovr: 85, image: 'assets/futgraphics/Iñigo_Martínez_Team of the Week.png' },
  { name: 'Iván Zamorano', ovr: 91, image: 'assets/futgraphics/Iván_Zamorano_Fantasy UT Hero.png' },
  { name: 'Jack Payne', ovr: 85, image: 'assets/futgraphics/Jack_Payne_Team of the Week.png' },
  { name: 'Jesús Rodríguez', ovr: 85, image: 'assets/futgraphics/Jesús_Rodríguez_Team of the Week.png' },
  { name: 'John Arne Riise', ovr: 91, image: 'assets/futgraphics/John_Arne_Riise_Fantasy UT Hero.png' },
  { name: 'Joshua Kimmich', ovr: 85, image: 'assets/futgraphics/Joshua_Kimmich_Team of the Week.png' },
  { name: 'Jurriën Timber', ovr: 85, image: 'assets/futgraphics/Jurriën_Timber_Team of the Week.png' },
  { name: 'Kiernan Dewsbury-Hall', ovr: 87, image: 'assets/futgraphics/Kiernan_Dewsbury-Hall_Special Item.png' },
  { name: 'Kristian Thorstvedt', ovr: 85, image: 'assets/futgraphics/Kristian_Thorstvedt_Team of the Week.png' },
  { name: 'Leandro Trossard', ovr: 87, image: 'assets/futgraphics/Leandro_Trossard_Special Item.png' },
  { name: 'Lewis Miley', ovr: 87, image: 'assets/futgraphics/Lewis_Miley_Fantasy UT.png' },
  { name: 'Lionel Messi', ovr: 85, image: 'assets/futgraphics/Lionel_Messi_Team of the Week.png' },
  { name: 'Marshall Munetsi', ovr: 85, image: 'assets/futgraphics/Marshall_Munetsi_Team of the Week.png' },
  { name: 'Martin Baturina', ovr: 87, image: 'assets/futgraphics/Martin_Baturina_Fantasy UT.png' },
  { name: 'Martín Satriano', ovr: 85, image: 'assets/futgraphics/Martín_Satriano_Team of the Week.png' },
  { name: 'Matheus Nunes', ovr: 87, image: 'assets/futgraphics/Matheus_Nunes_Special Item.png' },
  { name: 'Mathys Tel', ovr: 87, image: 'assets/futgraphics/Mathys_Tel_Special Item.png' },
  { name: 'Matteo Ruggeri', ovr: 87, image: 'assets/futgraphics/Matteo_Ruggeri_Fantasy UT.png' },
  { name: 'Mattéo Guendouzi', ovr: 87, image: 'assets/futgraphics/Mattéo_Guendouzi_Fantasy UT (1).png' },
  { name: 'Mattéo Guendouzi', ovr: 87, image: 'assets/futgraphics/Mattéo_Guendouzi_Fantasy UT.png' },
  { name: 'Michael Duffy', ovr: 85, image: 'assets/futgraphics/Michael_Duffy_Team of the Week.png' },
  { name: 'Mika Godts', ovr: 87, image: 'assets/futgraphics/Mika_Godts_Fantasy UT.png' },
  { name: 'Mikkel Damsgaard', ovr: 85, image: 'assets/futgraphics/Mikkel_Damsgaard_Team of the Week.png' },
  { name: 'Milos Kerkez', ovr: 87, image: 'assets/futgraphics/Milos_Kerkez_Special Item.png' },
  { name: 'Mohamed Ihattaren', ovr: 85, image: 'assets/futgraphics/Mohamed_Ihattaren_Team of the Week.png' },
  { name: 'Nathan Ngoy', ovr: 85, image: 'assets/futgraphics/Nathan_Ngoy_Team of the Week.png' },
  { name: 'Niclas Füllkrug', ovr: 87, image: 'assets/futgraphics/Niclas_Füllkrug_Fantasy UT.png' },
  { name: 'Nikola Vasilj', ovr: 85, image: 'assets/futgraphics/Nikola_Vasilj_Team of the Week.png' },
  { name: 'Odsonne Edouard', ovr: 87, image: 'assets/futgraphics/Odsonne_Edouard_Fantasy UT.png' },
  { name: 'Oscar Bobb', ovr: 87, image: 'assets/futgraphics/Oscar_Bobb_Fantasy UT.png' },
  { name: 'Pablo Aimar', ovr: 91, image: 'assets/futgraphics/Pablo_Aimar_Fantasy UT Hero.png' },
  { name: 'Park Ji Sung', ovr: 91, image: 'assets/futgraphics/Park_Ji_Sung_Fantasy UT Hero.png' },
  { name: 'Paul Onuachu', ovr: 87, image: 'assets/futgraphics/Paul_Onuachu_Fantasy UT.png' },
  { name: 'Pierre Kalulu', ovr: 87, image: 'assets/futgraphics/Pierre_Kalulu_Fantasy UT.png' },
  { name: 'Rafael Márquez', ovr: 91, image: 'assets/futgraphics/Rafael_Márquez_Fantasy UT Hero.png' },
  { name: 'Rafael Profini', ovr: 85, image: 'assets/futgraphics/Rafael_Profini_Team of the Week.png' },
  { name: 'Raheem Sterling', ovr: 87, image: 'assets/futgraphics/Raheem_Sterling_Fantasy UT.png' },
  { name: 'Rani Khedira', ovr: 85, image: 'assets/futgraphics/Rani_Khedira_Team of the Week.png' },
  { name: 'Raúl Jiménez', ovr: 87, image: 'assets/futgraphics/Raúl_Jiménez_Special Item.png' },
  { name: 'Robert Sánchez', ovr: 87, image: 'assets/futgraphics/Robert_Sánchez_Special Item.png' },
  { name: 'Rodrigo Zalazar', ovr: 85, image: 'assets/futgraphics/Rodrigo_Zalazar_Team of the Week.png' },
  { name: 'Romelu Lukaku', ovr: 85, image: 'assets/futgraphics/Romelu_Lukaku_Team of the Week.png' },
  { name: 'Sam Coffey', ovr: 87, image: 'assets/futgraphics/Sam_Coffey_Fantasy UT.png' },
  { name: 'Sepp van den Berg', ovr: 87, image: 'assets/futgraphics/Sepp_van_den_Berg_Fantasy UT.png' },
  { name: 'Thorgan Hazard', ovr: 85, image: 'assets/futgraphics/Thorgan_Hazard_Team of the Week.png' },
  { name: 'Tijjani Reijnders', ovr: 87, image: 'assets/futgraphics/Tijjani_Reijnders_Fantasy UT.png' },
  { name: 'Tim Cahill', ovr: 91, image: 'assets/futgraphics/Tim_Cahill_Fantasy UT Hero.png' },
  { name: 'Tristan Crama', ovr: 85, image: 'assets/futgraphics/Tristan_Crama_Team of the Week.png' },
  { name: 'Vangelis Pavlidis', ovr: 87, image: 'assets/futgraphics/Vangelis_Pavlidis_Fantasy UT.png' },
  { name: 'Viktor Gyökeres', ovr: 87, image: 'assets/futgraphics/Viktor_Gyökeres_Fantasy UT.png' },
  { name: 'Waldemar Anton', ovr: 87, image: 'assets/futgraphics/Waldemar_Anton_Fantasy UT.png' },
  { name: 'Warren Zaïre-Emery', ovr: 87, image: 'assets/futgraphics/Warren_Zaïre-Emery_Fantasy UT.png' },
  { name: 'Wesley Sneijder', ovr: 91, image: 'assets/futgraphics/Wesley_Sneijder_Fantasy UT Hero.png' },
  { name: 'Wifi', ovr: 88, image: 'assets/futgraphics/Wifi_POTM LIGA F.png' },
  { name: 'William Gomes', ovr: 85, image: 'assets/futgraphics/William_Gomes_Team of the Week.png' }
];

JOUEURS_COLLECTION = JOUEURS_COLLECTION.concat(JOUEURS_FUTGRAPHICS_FC26);

function getJoueursByOvr(minOvr, maxOvr) {
  return JOUEURS_COLLECTION.filter(function(p) {
    return p.ovr >= minOvr && p.ovr <= maxOvr;
  });
}
