var TRANSLATIONS = {
  fr: {
    homeTitle: 'Ultimate Challenge SAISON 1',
    settings: 'Paramètres',
    settings_sound: 'Son',
    language: 'Langue',
    lang_fr: 'Français',
    lang_en: 'English',
    lang_es: 'Español',
    lang_zh: '中文',
    game1: 'Mémoire de couleurs',
    game2: 'Jeu 2',
    game2_unlocked: 'Jeux de timer',
    game3: 'Jeu 3',
    game3_unlocked: 'Jeux de chance et stratégie',
    game4: 'Jeu 4',
    game5: 'Jeu 5',
    modal_warning_title: 'Attention',
    modal_warning_text: 'Si vous perdez une épreuve, vous devrez recommencer le jeu depuis le début.',
    modal_btn_start: 'Commencer',
    pintro_quete: 'Quête',
    pintro_marche: 'Marché',
    pintro_echange: 'Échange',
    pintro_boutique: 'Boutique',
    j1_btn_exit: 'Sortir',
    j1_rules_title: 'Règles du jeu',
    j1_rules_text: 'L\'ordinateur affiche une séquence de blocs colorés (rouge, jaune, vert, bleu). Mémorise-la puis reproduis-la en cliquant sur les couleurs dans le bon ordre. Deux épreuves : d\'abord 5 blocs, puis 9. Tu as un temps limité. Si tu te trompes ou que le temps est écoulé, tu perds.',
    j1_subtitle: 'Mémorise la séquence puis reproduis-la',
    j1_hint_click_start: 'Clique sur « Démarrer » pour voir la séquence.',
    j1_hint_watch: 'Regarde la séquence...',
    j1_hint_watch_ep2: 'Épreuve 2 : regarde la séquence...',
    j1_hint_reproduce: 'Reproduis la séquence.',
    j1_epreuve1: 'Épreuve 1',
    j1_epreuve2: 'Épreuve 2',
    j1_btn_start: 'Démarrer',
    j1_btn_replay: 'Rejouer',
    j1_btn_back_home: 'Retourner à la page d\'accueil',
    j1_result_win: 'Tu as gagné !',
    j1_result_lose: 'Perdu',
    j1_result_ep1_pass: 'Épreuve 1 réussie ! Passage à l\'épreuve 2 dans 2 secondes...',
    j1_result_ep2_pass: 'Épreuve 2 réussie !',
    j1_result_time: 'Temps écoulé !',
    j1_result_wrong: 'La séquence n\'est pas correcte.',
    j1_back_aria: 'Retour accueil',
    j2_instruction: 'Arrête le timer à 5 secondes (tolérance 0,05 s).',
    j2_rules_title: 'Règles du jeu',
    j2_rules_text: 'Un timer affiche les secondes et centièmes. Clique sur « Arrêter » quand tu penses avoir atteint 5 secondes. Tolérance : entre 4,95 s et 5,05 s. Si tu es en dehors, tu perds.',
    j2_btn_stop: 'Arrêter',
    j2_ep1_success_title: 'Étape 1 réussie !',
    j2_ep1_success_text: 'Passage à l\'étape 2...',
    j2_ep1_success_btn: 'Continuer',
    j2_ep2_rules_title: 'Étape 2',
    j2_ep2_rules_text: 'Le chronomètre est invisible. Lance-le avec « Démarrer », puis arrête-le entre la 15e et la 17e seconde avec « Arrêter ». Si tu es en dehors de cette fenêtre, tu perds.',
    j2_ep2_rules_extra: 'Si tu perds, tu pourras retenter pour 5000 💎 ou passer l\'épreuve pour 10000 💎 (après avoir échoué). Pour passer sans échouer, utilise le code.',
    j2_retry_btn: 'Retenter (5000 💎)',
    j2_pass_btn: 'Passer l\'épreuve (10 000 💎)',
    j2_not_enough_starcoins: 'Pas assez de Starcoins.',
    j2_confirm_retry_title: 'Confirmer le paiement',
    j2_confirm_retry_text: 'Payer 5000 💎 pour retenter ta chance ?',
    j2_confirm_pass_title: 'Confirmer le paiement',
    j2_confirm_pass_text: 'Payer 10 000 💎 pour passer l\'épreuve ?',
    j2_confirm_pay_btn: 'Confirmer',
    j2_cancel_btn: 'Annuler',
    j2_ep2_instruction: 'Chrono invisible : lance-le puis arrête entre 15 s et 17 s.',
    j2_btn_start: 'Démarrer',
    j2_ep2_lose_msg: 'Perdu. Il fallait arrêter entre 15 s et 17 s.',
    j2_skip_link: 'Passer l\'épreuve',
    j2_skip_modal_title: 'Passer l\'épreuve',
    j2_skip_placeholder: 'Mot de passe',
    j2_skip_wrong: 'Mot de passe incorrect',
    code_modal_title: 'Code requis',
    code_modal_placeholder: 'Entrez le code',
    code_modal_submit: 'Valider',
    code_modal_wrong: 'Code incorrect',
    j2_success: 'Bravo !',
    j2_result_time: 'Vous avez arrêté à',
    j2_lose_msg: 'Perdu. Il fallait entre 4,95 s et 5,05 s.',
    j2_btn_back: 'Retour à l\'accueil',
    j2_btn_restart: 'Recommencer',
    btn_quit: 'Quitter',
    game_bonus: 'Jeu bonus',
    game_bonus2: 'Quiz Histoire & Géo',
    jbonus_title: 'Quiz bonus – Football',
    jbonus_warning_title: 'Attention',
    jbonus_warning_text: 'Si tu perds ce bonus (une mauvaise réponse), tu pourras payer 20 000 💎 pour continuer ou quitter.',
    jbonus_warning_btn_start: 'Faire le bonus',
    jbonus_warning_no_thanks: 'Non merci',
    jbonus_question_of: 'Question',
    jbonus_of: ' / 5',
    jbonus_win_starcoin: 'Bravo ! Vous gagnez 100 000 Starcoins !',
    jbonus_lose_msg: 'Perdu. Vous n\'avez pas réussi les 5 questions.',
    jbonus_back: 'Retour à l\'accueil',
    jbonus_title_history: 'Quiz bonus – Histoire & Géographie',
    jbonus_continue_msg: 'Mauvaise réponse. Payer 20 000 Starcoins pour continuer le quiz ?',
    jbonus_pay_5000: 'Payer 20 000 💎',
    jbonus_quit_pintro: 'Quitter (retour pintro)',
    jbonus_exit_bonus_continue_challenge: 'Sortir du bonus mais continuer le challenge (20 000 💎)',
    jbonus_no_starcoins: 'Starcoins insuffisants (il en faut 20 000).',
    bonus_reminder_title: 'Rappel',
    bonus_reminder_text: 'Le jeu bonus est disponible. Fais-le pour faciliter les prochaines épreuves.',
    bonus_reminder_btn: 'OK',
    j3_rules_title: 'Règles du jeu',
    j3_rules_text: 'Il existe un parcours secret (ex. G G D G…). Tu dois traverser un pont de 7 rangées : à chaque rangée, choisis gauche ou droite. Une seule case est sûre par rangée. Tu peux acheter un bonhomme test (10 000 💎) : tu le contrôles, il fait le parcours à ta place. S\'il pose le pied sur une piège, il meurt (fin de tentative). Ensuite, achète un autre bonhomme test ou tente avec ton vrai joueur. Si ton vrai joueur tombe sur une piège, tu perds. Code 1428 pour passer.',
    j3_row_of: 'Rangée {n} / {total}',
    j3_left: 'Gauche',
    j3_right: 'Droite',
    j3_buy_dummy: 'Bonhomme test (10 000 💎)',
    j3_use_dummy: 'Utiliser le bonhomme test',
    j3_dummy_count: 'Bonhommes test :',
    j3_win_msg: 'Bravo ! Tu as traversé le pont !',
    j3_elite_title: 'Tu fais partie de l\'élite !',
    j3_elite_text: 'Félicitations, tu as réussi toutes les épreuves. Tu fais partie de l\'élite.',
    j3_lose_msg: 'Perdu !',
    j3_lose_explain: 'Tu es tombé sur une case piégée. Tu dois recommencer le jeu depuis le début (page d\'intro).',
    j3_buy_confirm_title: 'Confirmer l\'achat',
    j3_buy_confirm_text: 'Un bonhomme test coûte 10 000 💎. Il révélera la case sûre d\'une rangée. Confirmer ?',
    j3_buy_confirm_btn: 'Confirmer',
    j3_buy_cancel_btn: 'Annuler',
    j3_dummy_trap_title: 'Bonhomme test',
    j3_dummy_trap_text: 'Le bonhomme test est tombé sur une case piégée. Il n\'est plus utilisable. Il faudra en acheter un autre.',
    j3_dummy_trap_btn: 'OK',
    j3_dummy_label: 'bonhomme test',
    j3_dummy_success_title: 'Bonhomme test',
    j3_dummy_success_text: 'Le bonhomme test a traversé le pont ! Tu as vu le parcours. À toi de jouer.'
  },
  en: {
    homeTitle: 'Ultimate Challenge SEASON 1',
    settings: 'Settings',
    settings_sound: 'Sound',
    language: 'Language',
    lang_fr: 'Français',
    lang_en: 'English',
    lang_es: 'Español',
    lang_zh: '中文',
    game1: 'Color memory',
    game2: 'Game 2',
    game2_unlocked: 'Timer game',
    game3: 'Game 3',
    game3_unlocked: 'Chance and strategy games',
    game4: 'Game 4',
    game5: 'Game 5',
    modal_warning_title: 'Warning',
    modal_warning_text: 'If you lose a trial, you will have to start the game over from the beginning.',
    modal_btn_start: 'Start',
    pintro_quete: 'Quest',
    pintro_marche: 'Market',
    pintro_echange: 'Exchange',
    pintro_boutique: 'Shop',
    j1_btn_exit: 'Exit',
    j1_rules_title: 'Game rules',
    j1_rules_text: 'The computer shows a sequence of colored blocks (red, yellow, green, blue). Memorize it then reproduce it by clicking the colors in the correct order. Two trials: first 5 blocks, then 9. You have a time limit. If you make a mistake or time runs out, you lose.',
    j1_subtitle: 'Memorize the sequence then reproduce it',
    j1_hint_click_start: 'Click « Start » to see the sequence.',
    j1_hint_watch: 'Watch the sequence...',
    j1_hint_watch_ep2: 'Trial 2: watch the sequence...',
    j1_hint_reproduce: 'Reproduce the sequence.',
    j1_epreuve1: 'Trial 1',
    j1_epreuve2: 'Trial 2',
    j1_btn_start: 'Start',
    j1_btn_replay: 'Play again',
    j1_btn_back_home: 'Return to home page',
    j1_result_win: 'You won!',
    j1_result_lose: 'Lost',
    j1_result_ep1_pass: 'Trial 1 complete! Trial 2 in 2 seconds...',
    j1_result_ep2_pass: 'Trial 2 complete!',
    j1_result_time: 'Time\'s up!',
    j1_result_wrong: 'The sequence is incorrect.',
    j1_back_aria: 'Back to home',
    j2_instruction: 'Stop the timer at 5 seconds (0.05 s tolerance).',
    j2_rules_title: 'Game rules',
    j2_rules_text: 'A timer shows seconds and hundredths. Click « Stop » when you think you\'ve reached 5 seconds. Tolerance: between 4.95 s and 5.05 s. If you\'re outside that range, you lose.',
    j2_btn_stop: 'Stop',
    j2_ep1_success_title: 'Trial 1 complete!',
    j2_ep1_success_text: 'Moving to trial 2...',
    j2_ep1_success_btn: 'Continue',
    j2_ep2_rules_title: 'Trial 2',
    j2_ep2_rules_text: 'The stopwatch is invisible. Start it with « Start », then stop it between 15 and 17 seconds with « Stop ». If you\'re outside that window, you lose.',
    j2_ep2_rules_extra: 'If you lose, you can retry for 5000 💎 or skip the trial for 10000 💎 (after failing). To skip without failing, use the code.',
    j2_retry_btn: 'Retry (5000 💎)',
    j2_pass_btn: 'Skip trial (10,000 💎)',
    j2_not_enough_starcoins: 'Not enough Starcoins.',
    j2_confirm_retry_title: 'Confirm payment',
    j2_confirm_retry_text: 'Pay 5000 💎 to retry?',
    j2_confirm_pass_title: 'Confirm payment',
    j2_confirm_pass_text: 'Pay 10,000 💎 to skip this trial?',
    j2_confirm_pay_btn: 'Confirm',
    j2_cancel_btn: 'Cancel',
    j2_ep2_instruction: 'Invisible stopwatch: start it then stop between 15 s and 17 s.',
    j2_btn_start: 'Start',
    j2_ep2_lose_msg: 'Lost. You had to stop between 15 s and 17 s.',
    j2_skip_link: 'Skip trial',
    j2_skip_modal_title: 'Skip trial',
    j2_skip_placeholder: 'Password',
    j2_skip_wrong: 'Wrong password',
    code_modal_title: 'Code required',
    code_modal_placeholder: 'Enter code',
    code_modal_submit: 'Submit',
    code_modal_wrong: 'Wrong code',
    j2_success: 'Well done!',
    j2_result_time: 'You stopped at',
    j2_lose_msg: 'Lost. Target was between 4.95 s and 5.05 s.',
    j2_btn_back: 'Back to home',
    j2_btn_restart: 'Restart',
    btn_quit: 'Quit',
    game_bonus: 'Bonus game',
    game_bonus2: 'History & Geo Quiz',
    jbonus_title: 'Bonus quiz – Football',
    jbonus_warning_title: 'Warning',
    jbonus_warning_text: 'If you lose this bonus (one wrong answer), you can pay 20,000 💎 to continue or quit.',
    jbonus_warning_btn_start: 'Do the bonus',
    jbonus_warning_no_thanks: 'No thanks',
    jbonus_question_of: 'Question',
    jbonus_of: ' / 5',
    jbonus_win_starcoin: 'Well done! You win 100,000 Starcoins!',
    jbonus_lose_msg: 'Failed. You didn\'t get all 5 questions right.',
    jbonus_back: 'Back to home',
    jbonus_title_history: 'Bonus quiz – History & Geography',
    jbonus_continue_msg: 'Wrong answer. Pay 20,000 Starcoins to continue the quiz?',
    jbonus_pay_5000: 'Pay 20,000 💎',
    jbonus_quit_pintro: 'Quit (back to pintro)',
    jbonus_exit_bonus_continue_challenge: 'Exit bonus but continue the challenge (20,000 💎)',
    jbonus_no_starcoins: 'Not enough Starcoins (20,000 required).',
    bonus_reminder_title: 'Reminder',
    bonus_reminder_text: 'The bonus game is available. Play it to make the next trials easier.',
    bonus_reminder_btn: 'OK',
    j3_rules_title: 'Game rules',
    j3_rules_text: 'There is a secret path (e.g. L L R L…). You must cross a bridge of 7 rows: at each row choose left or right. Only one tile is safe per row. You can buy a test dummy (10,000 💎): you control it, it walks the path for you. If it steps on a trap, it dies (attempt over). Then buy another dummy or try with your real player. If your real player steps on a trap, you lose. Code 1428 to skip.',
    j3_row_of: 'Row {n} / {total}',
    j3_left: 'Left',
    j3_right: 'Right',
    j3_buy_dummy: 'Test dummy (10,000 💎)',
    j3_use_dummy: 'Use test dummy',
    j3_dummy_count: 'Test dummies:',
    j3_win_msg: 'Well done! You crossed the bridge!',
    j3_elite_title: 'You are part of the elite!',
    j3_elite_text: 'Congratulations, you have completed all trials. You are part of the elite.',
    j3_lose_msg: 'Lost!',
    j3_lose_explain: 'You stepped on a trap tile. You must start the game over from the beginning (intro page).',
    j3_buy_confirm_title: 'Confirm purchase',
    j3_buy_confirm_text: 'A test dummy costs 10,000 💎. It will reveal the safe tile for one row. Confirm?',
    j3_buy_confirm_btn: 'Confirm',
    j3_buy_cancel_btn: 'Cancel',
    j3_dummy_trap_title: 'Test dummy',
    j3_dummy_trap_text: 'The test dummy fell on a trap tile. It is no longer usable. You will need to buy another one.',
    j3_dummy_trap_btn: 'OK',
    j3_dummy_label: 'test dummy',
    j3_dummy_success_title: 'Test dummy',
    j3_dummy_success_text: 'The test dummy crossed the bridge! You have seen the path. Your turn.'
  },
  es: {
    homeTitle: 'Ultimate Challenge TEMPORADA 1',
    settings: 'Ajustes',
    settings_sound: 'Sonido',
    language: 'Idioma',
    lang_fr: 'Français',
    lang_en: 'English',
    lang_es: 'Español',
    lang_zh: '中文',
    game1: 'Memoria de colores',
    game2: 'Juego 2',
    game2_unlocked: 'Juego de timer',
    game3: 'Juego 3',
    game3_unlocked: 'Juegos de azar y estrategia',
    game4: 'Juego 4',
    game5: 'Juego 5',
    modal_warning_title: 'Atención',
    modal_warning_text: 'Si pierdes una prueba, tendrás que volver a empezar el juego desde el principio.',
    modal_btn_start: 'Comenzar',
    pintro_quete: 'Misión',
    pintro_marche: 'Mercado',
    pintro_echange: 'Intercambio',
    pintro_boutique: 'Tienda',
    j1_btn_exit: 'Salir',
    j1_rules_title: 'Reglas del juego',
    j1_rules_text: 'El ordenador muestra una secuencia de bloques de colores (rojo, amarillo, verde, azul). Memorízala y reprodúcela haciendo clic en los colores en el orden correcto. Dos pruebas: primero 5 bloques, luego 9. Tienes un tiempo limitado. Si te equivocas o se acaba el tiempo, pierdes.',
    j1_subtitle: 'Memoriza la secuencia y reprodúcela',
    j1_hint_click_start: 'Haz clic en « Iniciar » para ver la secuencia.',
    j1_hint_watch: 'Mira la secuencia...',
    j1_hint_watch_ep2: 'Prueba 2: mira la secuencia...',
    j1_hint_reproduce: 'Reproduce la secuencia.',
    j1_epreuve1: 'Prueba 1',
    j1_epreuve2: 'Prueba 2',
    j1_btn_start: 'Iniciar',
    j1_btn_replay: 'Jugar de nuevo',
    j1_btn_back_home: 'Volver a la página de inicio',
    j1_result_win: '¡Ganaste!',
    j1_result_lose: 'Perdido',
    j1_result_ep1_pass: '¡Prueba 1 completada! Prueba 2 en 2 segundos...',
    j1_result_ep2_pass: '¡Prueba 2 completada!',
    j1_result_time: '¡Se acabó el tiempo!',
    j1_result_wrong: 'La secuencia no es correcta.',
    j1_back_aria: 'Volver al inicio',
    j2_instruction: 'Detén el timer a 5 segundos (tolerancia 0,05 s).',
    j2_rules_title: 'Reglas del juego',
    j2_rules_text: 'Un timer muestra segundos y centésimas. Haz clic en « Detener » cuando creas haber llegado a 5 segundos. Tolerancia: entre 4,95 s y 5,05 s. Si te pasas, pierdes.',
    j2_btn_stop: 'Detener',
    j2_ep1_success_title: '¡Prueba 1 completada!',
    j2_ep1_success_text: 'Pasando a la prueba 2...',
    j2_ep1_success_btn: 'Continuar',
    j2_ep2_rules_title: 'Prueba 2',
    j2_ep2_rules_text: 'El cronómetro es invisible. Inícialo con « Iniciar », luego deténlo entre 15 y 17 segundos con « Detener ». Si te pasas de esa ventana, pierdes.',
    j2_ep2_rules_extra: 'Si pierdes, podrás reintentar por 5000 💎 o saltar la prueba por 10000 💎 (tras fallar). Para saltar sin fallar, usa el código.',
    j2_retry_btn: 'Reintentar (5000 💎)',
    j2_pass_btn: 'Saltar prueba (10 000 💎)',
    j2_not_enough_starcoins: 'No tienes suficientes Starcoins.',
    j2_confirm_retry_title: 'Confirmar pago',
    j2_confirm_retry_text: '¿Pagar 5000 💎 para reintentar?',
    j2_confirm_pass_title: 'Confirmar pago',
    j2_confirm_pass_text: '¿Pagar 10 000 💎 para saltar la prueba?',
    j2_confirm_pay_btn: 'Confirmar',
    j2_cancel_btn: 'Cancelar',
    j2_ep2_instruction: 'Cronómetro invisible: inícialo y detén entre 15 s y 17 s.',
    j2_btn_start: 'Iniciar',
    j2_ep2_lose_msg: 'Perdido. Había que detener entre 15 s y 17 s.',
    j2_skip_link: 'Saltar prueba',
    j2_skip_modal_title: 'Saltar prueba',
    j2_skip_placeholder: 'Contraseña',
    j2_skip_wrong: 'Contraseña incorrecta',
    code_modal_title: 'Código requerido',
    code_modal_placeholder: 'Introduce el código',
    code_modal_submit: 'Validar',
    code_modal_wrong: 'Código incorrecto',
    j2_success: '¡Bien!',
    j2_result_time: 'Detuviste a',
    j2_lose_msg: 'Perdido. Había que estar entre 4,95 s y 5,05 s.',
    j2_btn_back: 'Volver al inicio',
    j2_btn_restart: 'Reintentar',
    btn_quit: 'Salir',
    game_bonus: 'Juego bonus',
    game_bonus2: 'Quiz Historia y Geo',
    jbonus_title: 'Quiz bonus – Fútbol',
    jbonus_warning_title: 'Atención',
    jbonus_warning_text: 'Si pierdes este bonus (una respuesta incorrecta), podrás pagar 20 000 💎 para continuar o salir.',
    jbonus_warning_btn_start: 'Hacer el bonus',
    jbonus_warning_no_thanks: 'No gracias',
    jbonus_question_of: 'Pregunta',
    jbonus_of: ' / 5',
    jbonus_win_starcoin: '¡Enhorabuena! Ganas 100 000 Starcoins.',
    jbonus_lose_msg: 'Fallido. No has acertado las 5 preguntas.',
    jbonus_back: 'Volver al inicio',
    jbonus_title_history: 'Quiz bonus – Historia y Geografía',
    jbonus_continue_msg: 'Respuesta incorrecta. ¿Pagar 20 000 Starcoins para continuar el quiz?',
    jbonus_pay_5000: 'Pagar 20 000 💎',
    jbonus_quit_pintro: 'Salir (volver a pintro)',
    jbonus_exit_bonus_continue_challenge: 'Salir del bonus pero continuar el desafío (20 000 💎)',
    jbonus_no_starcoins: 'Starcoins insuficientes (se necesitan 20 000).',
    bonus_reminder_title: 'Recordatorio',
    bonus_reminder_text: 'El juego bonus está disponible. Juega para facilitar las próximas pruebas.',
    bonus_reminder_btn: 'OK',
    j3_rules_title: 'Reglas del juego',
    j3_rules_text: 'Existe un recorrido secreto (ej. I I D I…). Debes cruzar un puente de 7 filas: en cada fila elige izquierda o derecha. Solo una casilla es segura por fila. Puedes comprar un muñeco de prueba (10 000 💎): lo controlas, recorre el camino por ti. Si pisa una trampa, muere (fin del intento). Luego compra otro o intenta con tu jugador real. Si tu jugador real pisa una trampa, pierdes. Código 1428 para saltar.',
    j3_row_of: 'Fila {n} / {total}',
    j3_left: 'Izquierda',
    j3_right: 'Derecha',
    j3_buy_dummy: 'Muñeco de prueba (10 000 💎)',
    j3_use_dummy: 'Usar muñeco de prueba',
    j3_dummy_count: 'Muñecos de prueba:',
    j3_win_msg: '¡Bien! ¡Cruzaste el puente!',
    j3_elite_title: '¡Formas parte de la élite!',
    j3_elite_text: 'Enhorabuena, has superado todas las pruebas. Formas parte de la élite.',
    j3_lose_msg: '¡Perdido!',
    j3_lose_explain: 'Pisaste una casilla trampa. Debes volver a empezar el juego desde el principio (página de intro).',
    j3_buy_confirm_title: 'Confirmar compra',
    j3_buy_confirm_text: 'Un muñeco de prueba cuesta 10 000 💎. Revelará la casilla segura de una fila. ¿Confirmar?',
    j3_buy_confirm_btn: 'Confirmar',
    j3_buy_cancel_btn: 'Cancelar',
    j3_dummy_trap_title: 'Muñeco de prueba',
    j3_dummy_trap_text: 'El muñeco de prueba cayó en una casilla trampa. Ya no es utilizable. Tendrás que comprar otro.',
    j3_dummy_trap_btn: 'OK',
    j3_dummy_label: 'muñeco de prueba',
    j3_dummy_success_title: 'Muñeco de prueba',
    j3_dummy_success_text: '¡El muñeco de prueba cruzó el puente! Has visto el recorrido. Te toca a ti.'
  },
  zh: {
    homeTitle: 'Ultimate Challenge 第一季',
    settings: '设置',
    settings_sound: '声音',
    language: '语言',
    lang_fr: 'Français',
    lang_en: 'English',
    lang_es: 'Español',
    lang_zh: '中文',
    game1: '颜色记忆',
    game2: '游戏 2',
    game2_unlocked: '计时游戏',
    game3: '游戏 3',
    game3_unlocked: '运气与策略游戏',
    game4: '游戏 4',
    game5: '游戏 5',
    modal_warning_title: '注意',
    modal_warning_text: '如果输掉一关，你将需要从头重新开始游戏。',
    modal_btn_start: '开始',
    pintro_quete: '任务',
    pintro_marche: '市场',
    pintro_echange: '兑换',
    pintro_boutique: '商店',
    j1_btn_exit: '退出',
    j1_rules_title: '游戏规则',
    j1_rules_text: '电脑会显示一串彩色方块（红、黄、绿、蓝）。记住顺序后，按正确顺序点击颜色重现。两关：先5个方块，再9个。有时间限制。出错或超时即失败。',
    j1_subtitle: '记住顺序然后重现',
    j1_hint_click_start: '点击「开始」查看顺序。',
    j1_hint_watch: '看顺序...',
    j1_hint_watch_ep2: '第二关：看顺序...',
    j1_hint_reproduce: '重现顺序。',
    j1_epreuve1: '第一关',
    j1_epreuve2: '第二关',
    j1_btn_start: '开始',
    j1_btn_replay: '再玩一次',
    j1_btn_back_home: '返回首页',
    j1_result_win: '你赢了！',
    j1_result_lose: '失败',
    j1_result_ep1_pass: '第一关通过！2秒后进入第二关...',
    j1_result_ep2_pass: '第二关通过！',
    j1_result_time: '时间到！',
    j1_result_wrong: '顺序错误。',
    j1_back_aria: '返回首页',
    j2_instruction: '在 5 秒时停止计时器（误差 0.05 秒）。',
    j2_rules_title: '游戏规则',
    j2_rules_text: '计时器显示秒和百分之一秒。你认为达到 5 秒时点击「停止」。误差范围：4.95 秒至 5.05 秒。超出则失败。',
    j2_btn_stop: '停止',
    j2_ep1_success_title: '第一关通过！',
    j2_ep1_success_text: '进入第二关...',
    j2_ep1_success_btn: '继续',
    j2_ep2_rules_title: '第二关',
    j2_ep2_rules_text: '计时器不可见。点击「开始」启动，然后在 15 到 17 秒之间点击「停止」。超出此范围则失败。',
    j2_ep2_rules_extra: '失败后可支付 5000 💎 重试，或支付 10000 💎 跳过关卡。未失败时想跳过需输入代码。',
    j2_retry_btn: '重试（5000 💎）',
    j2_pass_btn: '跳过关卡（10 000 💎）',
    j2_not_enough_starcoins: 'Starcoins 不足。',
    j2_confirm_retry_title: '确认支付',
    j2_confirm_retry_text: '支付 5000 💎 重试？',
    j2_confirm_pass_title: '确认支付',
    j2_confirm_pass_text: '支付 10 000 💎 跳过关卡？',
    j2_confirm_pay_btn: '确认',
    j2_cancel_btn: '取消',
    j2_ep2_instruction: '隐形计时器：启动后请在 15 秒至 17 秒之间停止。',
    j2_btn_start: '开始',
    j2_ep2_lose_msg: '失败。需在 15 秒至 17 秒之间停止。',
    j2_skip_link: '跳过关卡',
    j2_skip_modal_title: '跳过关卡',
    j2_skip_placeholder: '密码',
    j2_skip_wrong: '密码错误',
    code_modal_title: '需要密码',
    code_modal_placeholder: '输入密码',
    code_modal_submit: '确认',
    code_modal_wrong: '密码错误',
    j2_success: '太棒了！',
    j2_result_time: '你停在了',
    j2_lose_msg: '失败。需要在 4.95 秒至 5.05 秒之间。',
    j2_btn_back: '返回首页',
    j2_btn_restart: '重新开始',
    btn_quit: '退出',
    game_bonus: 'Bonus 游戏',
    game_bonus2: '历史与地理测验',
    jbonus_title: 'Bonus 测验 – 足球',
    jbonus_warning_title: '注意',
    jbonus_warning_text: '若在此 bonus 中失败（答错一题），可支付 20 000 💎 继续或退出。',
    jbonus_warning_btn_start: '进行 bonus',
    jbonus_warning_no_thanks: '不用了',
    jbonus_question_of: '问题',
    jbonus_of: ' / 5',
    jbonus_win_starcoin: '恭喜！你获得 100 000 Starcoins！',
    jbonus_lose_msg: '未通过。未答对全部 5 题。',
    jbonus_back: '返回首页',
    jbonus_title_history: 'Bonus 测验 – 历史与地理',
    jbonus_continue_msg: '答错了。支付 20 000 Starcoins 继续测验？',
    jbonus_pay_5000: '支付 20 000 💎',
    jbonus_quit_pintro: '退出（返回 pintro）',
    jbonus_exit_bonus_continue_challenge: '退出 bonus 但继续挑战（20 000 💎）',
    jbonus_no_starcoins: 'Starcoins 不足（需要 20 000）。',
    bonus_reminder_title: '提醒',
    bonus_reminder_text: 'Bonus 游戏已开放。完成它可以让后续关卡更轻松。',
    bonus_reminder_btn: '确定',
    j3_rules_title: '游戏规则',
    j3_rules_text: '存在一条秘密路线（如 左左右左…）。需穿过 7 行桥，每行选左或右，只有一格安全。可购买测试人偶（10 000 💎）：由你操控，替你走路线。若踩中陷阱则死亡（该次尝试结束）。之后可再买一个人偶或用真实角色尝试。真实角色踩中陷阱则失败。输入 1428 可跳过关卡。',
    j3_row_of: '第 {n} / {total} 行',
    j3_left: '左',
    j3_right: '右',
    j3_buy_dummy: '测试人偶（10 000 💎）',
    j3_use_dummy: '使用测试人偶',
    j3_dummy_count: '测试人偶：',
    j3_win_msg: '恭喜！你过了桥！',
    j3_elite_title: '你已成为精英！',
    j3_elite_text: '恭喜你通过所有考验，你已成为精英。',
    j3_lose_msg: '失败！',
    j3_lose_explain: '你踩中了陷阱格。需要从介绍页重新开始游戏。',
    j3_buy_confirm_title: '确认购买',
    j3_buy_confirm_text: '一个测试人偶需要 10 000 💎，可显示一行的安全格。确认？',
    j3_buy_confirm_btn: '确认',
    j3_buy_cancel_btn: '取消',
    j3_dummy_trap_title: '测试人偶',
    j3_dummy_trap_text: '测试人偶踩中了陷阱格，已无法使用。需要重新购买一个。',
    j3_dummy_trap_btn: '确定',
    j3_dummy_label: '测试人偶',
    j3_dummy_success_title: '测试人偶',
    j3_dummy_success_text: '测试人偶过了桥！你已经看到路线。该你了。'
  }
};

window.getJ1Text = function(key) {
  var code = localStorage.getItem('clement-game-lang') || 'fr';
  var t = TRANSLATIONS[code] || TRANSLATIONS.fr;
  return t[key] !== undefined ? t[key] : key;
};

window.getText = function(key) {
  var code = localStorage.getItem('clement-game-lang') || 'fr';
  var t = TRANSLATIONS[code] || TRANSLATIONS.fr;
  return t[key] !== undefined ? t[key] : key;
};

window.setLang = function(code) {
  var t = TRANSLATIONS[code] || TRANSLATIONS.fr;
  localStorage.setItem('clement-game-lang', code);
  document.documentElement.lang = code === 'zh' ? 'zh-CN' : code;

  var title = document.getElementById('homeTitle');
  if (title) title.textContent = t.homeTitle;

  var settingsBtn = document.getElementById('settingsBtn');
  if (settingsBtn) {
    settingsBtn.textContent = t.settings;
    if (t.settings) settingsBtn.setAttribute('aria-label', t.settings);
  }

  document.querySelectorAll('[data-i18n]').forEach(function(el) {
    var key = el.getAttribute('data-i18n');
    if (t[key] !== undefined) {
      if (el.tagName === 'OPTION') return;
      el.textContent = t[key];
    }
  });

  document.querySelectorAll('select#langSelect option').forEach(function(opt) {
    var key = 'lang_' + opt.value;
    if (t[key] !== undefined) opt.textContent = t[key];
  });

  var soundCb = document.getElementById('soundCheckbox');
  if (soundCb && t.settings_sound) soundCb.setAttribute('aria-label', t.settings_sound);
};
