var TRANSLATIONS = {
  fr: {
    homeTitle: 'CLEMENT GAME SAISON 1',
    settings: 'Paramètres',
    language: 'Langue',
    lang_fr: 'Français',
    lang_en: 'English',
    lang_es: 'Español',
    lang_zh: '中文',
    game1: 'Mémoire de couleurs',
    game2: 'Jeu 2',
    game2_unlocked: 'Jeux de timer',
    game3: 'Jeu 3',
    game3_unlocked: 'Jeux de chance et stratégie',
    game4: 'Jeu 4',
    game5: 'Jeu 5',
    modal_warning_title: 'Attention',
    modal_warning_text: 'Si vous perdez une épreuve, vous devrez recommencer le jeu depuis le début.',
    modal_btn_start: 'Commencer',
    j1_btn_exit: 'Sortir',
    j1_rules_title: 'Règles du jeu',
    j1_rules_text: 'L\'ordinateur affiche une séquence de blocs colorés (rouge, jaune, vert, bleu). Mémorise-la puis reproduis-la en cliquant sur les couleurs dans le bon ordre. Deux épreuves : d\'abord 5 blocs, puis 9. Tu as un temps limité. Si tu te trompes ou que le temps est écoulé, tu perds.',
    j1_subtitle: 'Mémorise la séquence puis reproduis-la',
    j1_hint_click_start: 'Clique sur « Démarrer » pour voir la séquence.',
    j1_hint_watch: 'Regarde la séquence...',
    j1_hint_watch_ep2: 'Épreuve 2 : regarde la séquence...',
    j1_hint_reproduce: 'Reproduis la séquence.',
    j1_epreuve1: 'Épreuve 1',
    j1_epreuve2: 'Épreuve 2',
    j1_btn_start: 'Démarrer',
    j1_btn_replay: 'Rejouer',
    j1_btn_back_home: 'Retourner à la page d\'accueil',
    j1_result_win: 'Tu as gagné !',
    j1_result_lose: 'Perdu',
    j1_result_ep1_pass: 'Épreuve 1 réussie ! Passage à l\'épreuve 2 dans 2 secondes...',
    j1_result_ep2_pass: 'Épreuve 2 réussie !',
    j1_result_time: 'Temps écoulé !',
    j1_result_wrong: 'La séquence n\'est pas correcte.',
    j1_back_aria: 'Retour accueil',
    j2_instruction: 'Arrête le timer à 5 secondes (tolérance 0,05 s).',
    j2_rules_title: 'Règles du jeu',
    j2_rules_text: 'Un timer affiche les secondes et centièmes. Clique sur « Arrêter » quand tu penses avoir atteint 5 secondes. Tolérance : entre 4,95 s et 5,05 s. Si tu es en dehors, tu perds.',
    j2_btn_stop: 'Arrêter',
    j2_ep1_success_title: 'Étape 1 réussie !',
    j2_ep1_success_text: 'Passage à l\'étape 2...',
    j2_ep1_success_btn: 'Continuer',
    j2_ep2_rules_title: 'Étape 2',
    j2_ep2_rules_text: 'Le chronomètre est invisible. Lance-le avec « Démarrer », puis arrête-le entre la 15e et la 17e seconde avec « Arrêter ». Si tu es en dehors de cette fenêtre, tu perds.',
    j2_ep2_instruction: 'Chrono invisible : lance-le puis arrête entre 15 s et 17 s.',
    j2_btn_start: 'Démarrer',
    j2_ep2_lose_msg: 'Perdu. Il fallait arrêter entre 15 s et 17 s.',
    j2_skip_link: 'Passer l\'épreuve',
    j2_skip_modal_title: 'Passer l\'épreuve',
    j2_skip_placeholder: 'Mot de passe',
    j2_skip_wrong: 'Mot de passe incorrect',
    code_modal_title: 'Code requis',
    code_modal_placeholder: 'Entrez le code',
    code_modal_submit: 'Valider',
    code_modal_wrong: 'Code incorrect',
    j2_success: 'Bravo !',
    j2_result_time: 'Vous avez arrêté à',
    j2_lose_msg: 'Perdu. Il fallait entre 4,95 s et 5,05 s.',
    j2_btn_back: 'Retour à l\'accueil',
    j2_btn_restart: 'Recommencer',
    game_bonus: 'Jeu bonus',
    jbonus_title: 'Quiz bonus – Football',
    jbonus_question_of: 'Question',
    jbonus_of: ' / 5',
    jbonus_win_starcoin: 'Bravo ! Vous gagnez 100 000 Starcoins !',
    jbonus_lose_msg: 'Perdu. Vous n\'avez pas réussi les 5 questions. Le bouton bonus disparaît.',
    jbonus_back: 'Retour à l\'accueil',
    bonus_reminder_title: 'Rappel',
    bonus_reminder_text: 'Le jeu bonus est disponible. Fais-le pour faciliter les prochaines épreuves.',
    bonus_reminder_btn: 'OK',
    j3_rules_title: 'Règles du jeu',
    j3_rules_text: 'Tu dois traverser un pont de 7 rangées. Chaque rangée a deux cases : gauche et droite. Une seule est sûre, l\'autre est piégée. Choisis gauche ou droite à chaque pas. Si tu tombes sur la mauvaise case, tu perds et retournes au début. Tu peux acheter un bonhomme test (10 000 ⭐) pour qu\'il révèle la case sûre d\'une rangée. Code 1428 pour passer l\'épreuve.',
    j3_row_of: 'Rangée {n} / {total}',
    j3_left: 'Gauche',
    j3_right: 'Droite',
    j3_buy_dummy: 'Bonhomme test (10 000 ⭐)',
    j3_use_dummy: 'Utiliser le bonhomme test',
    j3_dummy_count: 'Bonhommes test :',
    j3_win_msg: 'Bravo ! Tu as traversé le pont !',
    j3_lose_msg: 'Perdu !',
    j3_lose_explain: 'Tu es tombé sur une case piégée. Tu dois recommencer le jeu depuis le début (page d\'intro).',
    j3_buy_confirm_title: 'Confirmer l\'achat',
    j3_buy_confirm_text: 'Un bonhomme test coûte 10 000 ⭐. Il révélera la case sûre d\'une rangée. Confirmer ?',
    j3_buy_confirm_btn: 'Confirmer',
    j3_buy_cancel_btn: 'Annuler',
    j3_dummy_trap_title: 'Bonhomme test',
    j3_dummy_trap_text: 'Le bonhomme test est tombé sur une case piégée. Il n\'est plus utilisable. Il faudra en acheter un autre.',
    j3_dummy_trap_btn: 'OK'
  },
  en: {
    homeTitle: 'CLEMENT GAME SEASON 1',
    settings: 'Settings',
    language: 'Language',
    lang_fr: 'Français',
    lang_en: 'English',
    lang_es: 'Español',
    lang_zh: '中文',
    game1: 'Color memory',
    game2: 'Game 2',
    game2_unlocked: 'Timer game',
    game3: 'Game 3',
    game3_unlocked: 'Chance and strategy games',
    game4: 'Game 4',
    game5: 'Game 5',
    modal_warning_title: 'Warning',
    modal_warning_text: 'If you lose a trial, you will have to start the game over from the beginning.',
    modal_btn_start: 'Start',
    j1_btn_exit: 'Exit',
    j1_rules_title: 'Game rules',
    j1_rules_text: 'The computer shows a sequence of colored blocks (red, yellow, green, blue). Memorize it then reproduce it by clicking the colors in the correct order. Two trials: first 5 blocks, then 9. You have a time limit. If you make a mistake or time runs out, you lose.',
    j1_subtitle: 'Memorize the sequence then reproduce it',
    j1_hint_click_start: 'Click « Start » to see the sequence.',
    j1_hint_watch: 'Watch the sequence...',
    j1_hint_watch_ep2: 'Trial 2: watch the sequence...',
    j1_hint_reproduce: 'Reproduce the sequence.',
    j1_epreuve1: 'Trial 1',
    j1_epreuve2: 'Trial 2',
    j1_btn_start: 'Start',
    j1_btn_replay: 'Play again',
    j1_btn_back_home: 'Return to home page',
    j1_result_win: 'You won!',
    j1_result_lose: 'Lost',
    j1_result_ep1_pass: 'Trial 1 complete! Trial 2 in 2 seconds...',
    j1_result_ep2_pass: 'Trial 2 complete!',
    j1_result_time: 'Time\'s up!',
    j1_result_wrong: 'The sequence is incorrect.',
    j1_back_aria: 'Back to home',
    j2_instruction: 'Stop the timer at 5 seconds (0.05 s tolerance).',
    j2_rules_title: 'Game rules',
    j2_rules_text: 'A timer shows seconds and hundredths. Click « Stop » when you think you\'ve reached 5 seconds. Tolerance: between 4.95 s and 5.05 s. If you\'re outside that range, you lose.',
    j2_btn_stop: 'Stop',
    j2_ep1_success_title: 'Trial 1 complete!',
    j2_ep1_success_text: 'Moving to trial 2...',
    j2_ep1_success_btn: 'Continue',
    j2_ep2_rules_title: 'Trial 2',
    j2_ep2_rules_text: 'The stopwatch is invisible. Start it with « Start », then stop it between 15 and 17 seconds with « Stop ». If you\'re outside that window, you lose.',
    j2_ep2_instruction: 'Invisible stopwatch: start it then stop between 15 s and 17 s.',
    j2_btn_start: 'Start',
    j2_ep2_lose_msg: 'Lost. You had to stop between 15 s and 17 s.',
    j2_skip_link: 'Skip trial',
    j2_skip_modal_title: 'Skip trial',
    j2_skip_placeholder: 'Password',
    j2_skip_wrong: 'Wrong password',
    code_modal_title: 'Code required',
    code_modal_placeholder: 'Enter code',
    code_modal_submit: 'Submit',
    code_modal_wrong: 'Wrong code',
    j2_success: 'Well done!',
    j2_result_time: 'You stopped at',
    j2_lose_msg: 'Lost. Target was between 4.95 s and 5.05 s.',
    j2_btn_back: 'Back to home',
    j2_btn_restart: 'Restart',
    game_bonus: 'Bonus game',
    jbonus_title: 'Bonus quiz – Football',
    jbonus_question_of: 'Question',
    jbonus_of: ' / 5',
    jbonus_win_starcoin: 'Well done! You win 100,000 Starcoins!',
    jbonus_lose_msg: 'Failed. You didn\'t get all 5 questions right. The bonus button will disappear.',
    jbonus_back: 'Back to home',
    bonus_reminder_title: 'Reminder',
    bonus_reminder_text: 'The bonus game is available. Play it to make the next trials easier.',
    bonus_reminder_btn: 'OK',
    j3_rules_title: 'Game rules',
    j3_rules_text: 'You must cross a bridge of 7 rows. Each row has two tiles: left and right. Only one is safe, the other is a trap. Choose left or right at each step. If you step on the wrong tile, you lose and go back to the start. You can buy a test dummy (10,000 ⭐) to reveal the safe tile for one row. Code 1428 to skip.',
    j3_row_of: 'Row {n} / {total}',
    j3_left: 'Left',
    j3_right: 'Right',
    j3_buy_dummy: 'Test dummy (10,000 ⭐)',
    j3_use_dummy: 'Use test dummy',
    j3_dummy_count: 'Test dummies:',
    j3_win_msg: 'Well done! You crossed the bridge!',
    j3_lose_msg: 'Lost!',
    j3_lose_explain: 'You stepped on a trap tile. You must start the game over from the beginning (intro page).',
    j3_buy_confirm_title: 'Confirm purchase',
    j3_buy_confirm_text: 'A test dummy costs 10,000 ⭐. It will reveal the safe tile for one row. Confirm?',
    j3_buy_confirm_btn: 'Confirm',
    j3_buy_cancel_btn: 'Cancel',
    j3_dummy_trap_title: 'Test dummy',
    j3_dummy_trap_text: 'The test dummy fell on a trap tile. It is no longer usable. You will need to buy another one.',
    j3_dummy_trap_btn: 'OK'
  },
  es: {
    homeTitle: 'CLEMENT GAME TEMPORADA 1',
    settings: 'Ajustes',
    language: 'Idioma',
    lang_fr: 'Français',
    lang_en: 'English',
    lang_es: 'Español',
    lang_zh: '中文',
    game1: 'Memoria de colores',
    game2: 'Juego 2',
    game2_unlocked: 'Juego de timer',
    game3: 'Juego 3',
    game3_unlocked: 'Juegos de azar y estrategia',
    game4: 'Juego 4',
    game5: 'Juego 5',
    modal_warning_title: 'Atención',
    modal_warning_text: 'Si pierdes una prueba, tendrás que volver a empezar el juego desde el principio.',
    modal_btn_start: 'Comenzar',
    j1_btn_exit: 'Salir',
    j1_rules_title: 'Reglas del juego',
    j1_rules_text: 'El ordenador muestra una secuencia de bloques de colores (rojo, amarillo, verde, azul). Memorízala y reprodúcela haciendo clic en los colores en el orden correcto. Dos pruebas: primero 5 bloques, luego 9. Tienes un tiempo limitado. Si te equivocas o se acaba el tiempo, pierdes.',
    j1_subtitle: 'Memoriza la secuencia y reprodúcela',
    j1_hint_click_start: 'Haz clic en « Iniciar » para ver la secuencia.',
    j1_hint_watch: 'Mira la secuencia...',
    j1_hint_watch_ep2: 'Prueba 2: mira la secuencia...',
    j1_hint_reproduce: 'Reproduce la secuencia.',
    j1_epreuve1: 'Prueba 1',
    j1_epreuve2: 'Prueba 2',
    j1_btn_start: 'Iniciar',
    j1_btn_replay: 'Jugar de nuevo',
    j1_btn_back_home: 'Volver a la página de inicio',
    j1_result_win: '¡Ganaste!',
    j1_result_lose: 'Perdido',
    j1_result_ep1_pass: '¡Prueba 1 completada! Prueba 2 en 2 segundos...',
    j1_result_ep2_pass: '¡Prueba 2 completada!',
    j1_result_time: '¡Se acabó el tiempo!',
    j1_result_wrong: 'La secuencia no es correcta.',
    j1_back_aria: 'Volver al inicio',
    j2_instruction: 'Detén el timer a 5 segundos (tolerancia 0,05 s).',
    j2_rules_title: 'Reglas del juego',
    j2_rules_text: 'Un timer muestra segundos y centésimas. Haz clic en « Detener » cuando creas haber llegado a 5 segundos. Tolerancia: entre 4,95 s y 5,05 s. Si te pasas, pierdes.',
    j2_btn_stop: 'Detener',
    j2_ep1_success_title: '¡Prueba 1 completada!',
    j2_ep1_success_text: 'Pasando a la prueba 2...',
    j2_ep1_success_btn: 'Continuar',
    j2_ep2_rules_title: 'Prueba 2',
    j2_ep2_rules_text: 'El cronómetro es invisible. Inícialo con « Iniciar », luego deténlo entre 15 y 17 segundos con « Detener ». Si te pasas de esa ventana, pierdes.',
    j2_ep2_instruction: 'Cronómetro invisible: inícialo y detén entre 15 s y 17 s.',
    j2_btn_start: 'Iniciar',
    j2_ep2_lose_msg: 'Perdido. Había que detener entre 15 s y 17 s.',
    j2_skip_link: 'Saltar prueba',
    j2_skip_modal_title: 'Saltar prueba',
    j2_skip_placeholder: 'Contraseña',
    j2_skip_wrong: 'Contraseña incorrecta',
    code_modal_title: 'Código requerido',
    code_modal_placeholder: 'Introduce el código',
    code_modal_submit: 'Validar',
    code_modal_wrong: 'Código incorrecto',
    j2_success: '¡Bien!',
    j2_result_time: 'Detuviste a',
    j2_lose_msg: 'Perdido. Había que estar entre 4,95 s y 5,05 s.',
    j2_btn_back: 'Volver al inicio',
    j2_btn_restart: 'Reintentar',
    game_bonus: 'Juego bonus',
    jbonus_title: 'Quiz bonus – Fútbol',
    jbonus_question_of: 'Pregunta',
    jbonus_of: ' / 5',
    jbonus_win_starcoin: '¡Enhorabuena! Ganas 100 000 Starcoins.',
    jbonus_lose_msg: 'Fallido. No has acertado las 5 preguntas. El botón bonus desaparecerá.',
    jbonus_back: 'Volver al inicio',
    bonus_reminder_title: 'Recordatorio',
    bonus_reminder_text: 'El juego bonus está disponible. Juega para facilitar las próximas pruebas.',
    bonus_reminder_btn: 'OK',
    j3_rules_title: 'Reglas del juego',
    j3_rules_text: 'Debes cruzar un puente de 7 filas. Cada fila tiene dos casillas: izquierda y derecha. Solo una es segura, la otra es trampa. Elige izquierda o derecha en cada paso. Si pisas la casilla equivocada, pierdes y vuelves al inicio. Puedes comprar un muñeco de prueba (10 000 ⭐) para revelar la casilla segura de una fila. Código 1428 para saltar.',
    j3_row_of: 'Fila {n} / {total}',
    j3_left: 'Izquierda',
    j3_right: 'Derecha',
    j3_buy_dummy: 'Muñeco de prueba (10 000 ⭐)',
    j3_use_dummy: 'Usar muñeco de prueba',
    j3_dummy_count: 'Muñecos de prueba:',
    j3_win_msg: '¡Bien! ¡Cruzaste el puente!',
    j3_lose_msg: '¡Perdido!',
    j3_lose_explain: 'Pisaste una casilla trampa. Debes volver a empezar el juego desde el principio (página de intro).',
    j3_buy_confirm_title: 'Confirmar compra',
    j3_buy_confirm_text: 'Un muñeco de prueba cuesta 10 000 ⭐. Revelará la casilla segura de una fila. ¿Confirmar?',
    j3_buy_confirm_btn: 'Confirmar',
    j3_buy_cancel_btn: 'Cancelar',
    j3_dummy_trap_title: 'Muñeco de prueba',
    j3_dummy_trap_text: 'El muñeco de prueba cayó en una casilla trampa. Ya no es utilizable. Tendrás que comprar otro.',
    j3_dummy_trap_btn: 'OK'
  },
  zh: {
    homeTitle: 'CLEMENT GAME 第一季',
    settings: '设置',
    language: '语言',
    lang_fr: 'Français',
    lang_en: 'English',
    lang_es: 'Español',
    lang_zh: '中文',
    game1: '颜色记忆',
    game2: '游戏 2',
    game2_unlocked: '计时游戏',
    game3: '游戏 3',
    game3_unlocked: '运气与策略游戏',
    game4: '游戏 4',
    game5: '游戏 5',
    modal_warning_title: '注意',
    modal_warning_text: '如果输掉一关，你将需要从头重新开始游戏。',
    modal_btn_start: '开始',
    j1_btn_exit: '退出',
    j1_rules_title: '游戏规则',
    j1_rules_text: '电脑会显示一串彩色方块（红、黄、绿、蓝）。记住顺序后，按正确顺序点击颜色重现。两关：先5个方块，再9个。有时间限制。出错或超时即失败。',
    j1_subtitle: '记住顺序然后重现',
    j1_hint_click_start: '点击「开始」查看顺序。',
    j1_hint_watch: '看顺序...',
    j1_hint_watch_ep2: '第二关：看顺序...',
    j1_hint_reproduce: '重现顺序。',
    j1_epreuve1: '第一关',
    j1_epreuve2: '第二关',
    j1_btn_start: '开始',
    j1_btn_replay: '再玩一次',
    j1_btn_back_home: '返回首页',
    j1_result_win: '你赢了！',
    j1_result_lose: '失败',
    j1_result_ep1_pass: '第一关通过！2秒后进入第二关...',
    j1_result_ep2_pass: '第二关通过！',
    j1_result_time: '时间到！',
    j1_result_wrong: '顺序错误。',
    j1_back_aria: '返回首页',
    j2_instruction: '在 5 秒时停止计时器（误差 0.05 秒）。',
    j2_rules_title: '游戏规则',
    j2_rules_text: '计时器显示秒和百分之一秒。你认为达到 5 秒时点击「停止」。误差范围：4.95 秒至 5.05 秒。超出则失败。',
    j2_btn_stop: '停止',
    j2_ep1_success_title: '第一关通过！',
    j2_ep1_success_text: '进入第二关...',
    j2_ep1_success_btn: '继续',
    j2_ep2_rules_title: '第二关',
    j2_ep2_rules_text: '计时器不可见。点击「开始」启动，然后在 15 到 17 秒之间点击「停止」。超出此范围则失败。',
    j2_ep2_instruction: '隐形计时器：启动后请在 15 秒至 17 秒之间停止。',
    j2_btn_start: '开始',
    j2_ep2_lose_msg: '失败。需在 15 秒至 17 秒之间停止。',
    j2_skip_link: '跳过关卡',
    j2_skip_modal_title: '跳过关卡',
    j2_skip_placeholder: '密码',
    j2_skip_wrong: '密码错误',
    code_modal_title: '需要密码',
    code_modal_placeholder: '输入密码',
    code_modal_submit: '确认',
    code_modal_wrong: '密码错误',
    j2_success: '太棒了！',
    j2_result_time: '你停在了',
    j2_lose_msg: '失败。需要在 4.95 秒至 5.05 秒之间。',
    j2_btn_back: '返回首页',
    j2_btn_restart: '重新开始',
    game_bonus: 'Bonus 游戏',
    jbonus_title: 'Bonus 测验 – 足球',
    jbonus_question_of: '问题',
    jbonus_of: ' / 5',
    jbonus_win_starcoin: '恭喜！你获得 100 000 Starcoins！',
    jbonus_lose_msg: '未通过。未答对全部 5 题。Bonus 按钮将消失。',
    jbonus_back: '返回首页',
    bonus_reminder_title: '提醒',
    bonus_reminder_text: 'Bonus 游戏已开放。完成它可以让后续关卡更轻松。',
    bonus_reminder_btn: '确定',
    j3_rules_title: '游戏规则',
    j3_rules_text: '你需要穿过一座 7 行的桥。每行有两格：左和右。只有一格是安全的，另一格是陷阱。每步选择左或右。踩错则失败并从头开始。可购买测试人偶（10 000 ⭐）来显示一行的安全格。输入 1428 可跳过关卡。',
    j3_row_of: '第 {n} / {total} 行',
    j3_left: '左',
    j3_right: '右',
    j3_buy_dummy: '测试人偶（10 000 ⭐）',
    j3_use_dummy: '使用测试人偶',
    j3_dummy_count: '测试人偶：',
    j3_win_msg: '恭喜！你过了桥！',
    j3_lose_msg: '失败！',
    j3_lose_explain: '你踩中了陷阱格。需要从介绍页重新开始游戏。',
    j3_buy_confirm_title: '确认购买',
    j3_buy_confirm_text: '一个测试人偶需要 10 000 ⭐，可显示一行的安全格。确认？',
    j3_buy_confirm_btn: '确认',
    j3_buy_cancel_btn: '取消',
    j3_dummy_trap_title: '测试人偶',
    j3_dummy_trap_text: '测试人偶踩中了陷阱格，已无法使用。需要重新购买一个。',
    j3_dummy_trap_btn: '确定'
  }
};

window.getJ1Text = function(key) {
  var code = localStorage.getItem('clement-game-lang') || 'fr';
  var t = TRANSLATIONS[code] || TRANSLATIONS.fr;
  return t[key] !== undefined ? t[key] : key;
};

window.getText = function(key) {
  var code = localStorage.getItem('clement-game-lang') || 'fr';
  var t = TRANSLATIONS[code] || TRANSLATIONS.fr;
  return t[key] !== undefined ? t[key] : key;
};

window.setLang = function(code) {
  var t = TRANSLATIONS[code] || TRANSLATIONS.fr;
  localStorage.setItem('clement-game-lang', code);
  document.documentElement.lang = code === 'zh' ? 'zh-CN' : code;

  var title = document.getElementById('homeTitle');
  if (title) title.textContent = t.homeTitle;

  var settingsBtn = document.getElementById('settingsBtn');
  if (settingsBtn) settingsBtn.textContent = t.settings;

  document.querySelectorAll('[data-i18n]').forEach(function(el) {
    var key = el.getAttribute('data-i18n');
    if (t[key] !== undefined) {
      if (el.tagName === 'OPTION') return;
      el.textContent = t[key];
    }
  });

  document.querySelectorAll('select#langSelect option').forEach(function(opt) {
    var key = 'lang_' + opt.value;
    if (t[key] !== undefined) opt.textContent = t[key];
  });
};
