/** Liste des 100 monuments – images réelles (Wikimedia Commons ou locales) */
var W = 'https://upload.wikimedia.org/wikipedia/commons/thumb';
window.MONUMENTS_COLLECTION = [
  { id: 'parthenon', name: 'Parthénon', image: W + '/8/8f/Parthenon_from_south.jpg/640px-Parthenon_from_south.jpg' },
  { id: 'basilique-saint-pierre', name: 'Basilique Saint-Pierre', image: 'assets/monuments/basilique-saint-pierre.png' },
  { id: 'neuschwanstein', name: 'Château de Neuschwanstein', image: W + '/a/ae/Castle_Neuschwanstein.jpg/640px-Castle_Neuschwanstein.jpg' },
  { id: 'stonehenge', name: 'Stonehenge', image: 'assets/monuments/stonehenge.png' },
  { id: 'mosquee-bleue', name: 'Mosquée Bleue', image: 'assets/monuments/mosquee-bleue.png' },
  { id: 'palais-westminster', name: 'Palais de Westminster', image: 'assets/monuments/palais-westminster.png' },
  { id: 'mont-rushmore', name: 'Mont Rushmore', image: 'assets/monuments/mont-rushmore.png' },
  { id: 'lincoln-memorial', name: 'Lincoln Memorial', image: 'assets/monuments/lincoln-memorial.png' },
  { id: 'tour-eiffel', name: 'Tour Eiffel', image: W + '/a/a8/Tour_Eiffel_Wikimedia_Commons.jpg/640px-Tour_Eiffel_Wikimedia_Commons.jpg' },
  { id: 'statue-liberte', name: 'Statue de la Liberté', image: W + '/d/d3/Statue_of_Liberty%2C_NY.jpg/640px-Statue_of_Liberty%2C_NY.jpg' },
  { id: 'colisee-rome', name: 'Colisée de Rome', image: W + '/5/53/Colosseum_in_Rome%2C_Italy_-_April_2007.jpg/640px-Colosseum_in_Rome%2C_Italy_-_April_2007.jpg' },
  { id: 'taj-mahal', name: 'Taj Mahal', image: W + '/1/15/Taj_Mahal.jpg/640px-Taj_Mahal.jpg' },
  { id: 'grande-muraille-chine', name: 'Grande Muraille de Chine', image: W + '/f/fa/Great_Wall_of_China_July_2006.JPG/640px-Great_Wall_of_China_July_2006.JPG' },
  { id: 'burj-khalifa', name: 'Burj Khalifa', image: 'assets/monuments/burj-khalifa.png' },
  { id: 'pyramides-gizeh', name: 'Pyramides de Gizeh', image: 'assets/monuments/pyramides-gizeh.png' },
  { id: 'machu-picchu', name: 'Machu Picchu', image: 'assets/monuments/machu-picchu.png' },
  { id: 'angkor-wat', name: 'Angkor Wat', image: 'assets/monuments/angkor-wat.png' },
  { id: 'petra', name: 'Pétra', image: 'assets/monuments/petra.png' },
  { id: 'big-ben', name: 'Big Ben', image: 'assets/monuments/big-ben.png' },
  { id: 'empire-state', name: 'Empire State Building', image: 'assets/monuments/empire-state.png' },
  { id: 'golden-gate', name: 'Golden Gate Bridge', image: 'assets/monuments/golden-gate.png' },
  { id: 'sydney-opera', name: 'Opéra de Sydney', image: 'assets/monuments/sydney-opera.png' },
  { id: 'tower-bridge', name: 'Tower Bridge', image: 'assets/monuments/tower-bridge.png' },
  { id: 'sainte-sophie', name: 'Sainte-Sophie', image: 'assets/monuments/sainte-sophie.png' },
  { id: 'notre-dame-paris', name: 'Notre-Dame de Paris', image: 'assets/monuments/notre-dame-paris.png' },
  { id: 'sagrada-familia', name: 'Sagrada Familia', image: 'assets/monuments/sagrada-familia.png' },
  { id: 'cathédrale-saint-basile', name: 'Cathédrale Saint-Basile', image: 'assets/monuments/cathedrale-saint-basile.png' },
  { id: 'chichen-itza', name: 'Chichen Itza', image: 'assets/monuments/chichen-itza.png' },
  { id: 'christ-redempteur', name: 'Christ Rédempteur', image: 'assets/monuments/christ-redempteur.png' },
  { id: 'tour-pise', name: 'Tour de Pise', image: 'assets/monuments/tour-pise.png' },
  { id: 'acropole', name: 'Acropole d\'Athènes', image: 'assets/monuments/acropole.png' },
  { id: 'alhambra', name: 'Alhambra', image: 'assets/monuments/alhambra.png' },
  { id: 'brandenburg', name: 'Porte de Brandebourg', image: 'assets/monuments/brandenburg.png' },
  { id: 'kremlin', name: 'Kremlin', image: 'assets/monuments/kremlin.png' },
  { id: 'forbidden-city', name: 'Cité interdite', image: 'assets/monuments/forbidden-city.png' },
  { id: 'anitkabir', name: 'Anıtkabir', image: 'assets/monuments/anitkabir.png' },
  { id: 'arc-triomphe', name: 'Arc de triomphe', image: 'assets/monuments/arc-triomphe.png' },
  { id: 'arc-triomphe-detail', name: 'Arc de triomphe (détail)', image: 'assets/monuments/arc-triomphe-detail.png' },
  { id: 'niagara-falls', name: 'Chutes du Niagara', image: 'assets/monuments/niagara-falls.png' },
  { id: 'grand-canyon', name: 'Grand Canyon', image: 'assets/monuments/grand-canyon.png' },
  { id: 'mount-rushmore', name: 'Mont Rushmore', image: 'assets/monuments/mont-rushmore.png' },
  { id: 'space-needle', name: 'Space Needle', image: 'assets/monuments/space-needle.png' },
  { id: 'cn-tower', name: 'Tour CN', image: 'assets/monuments/cn-tower.png' },
  { id: 'atomium', name: 'Atomium', image: 'assets/monuments/atomium.png' },
  { id: 'tour-london', name: 'Tour de Londres', image: 'assets/monuments/tour-london.png' },
  { id: 'westminster-abbey', name: 'Abbaye de Westminster', image: 'assets/monuments/westminster-abbey.png' },
  { id: 'buckingham', name: 'Buckingham Palace', image: 'assets/monuments/buckingham.png' },
  { id: 'saint-paul', name: 'Cathédrale Saint-Paul', image: 'assets/monuments/saint-paul.png' },
  { id: 'leaning-tower', name: 'Tour penchée de Pise', image: 'assets/monuments/tour-pise.png' },
  { id: 'pantheon-rome', name: 'Panthéon de Rome', image: 'assets/monuments/pantheon-rome.png' },
  { id: 'fontana-trevi', name: 'Fontaine de Trevi', image: 'assets/monuments/fontana-trevi.png' },
  { id: 'sphinx', name: 'Grand Sphinx', image: 'assets/monuments/sphinx.png' },
  { id: 'temple-bayon', name: 'Temple Bayon', image: 'assets/monuments/temple-bayon.png' },
  { id: 'borobudur', name: 'Borobudur', image: 'assets/monuments/borobudur.png' },
  { id: 'grand-buddha', name: 'Grand Bouddha de Leshan', image: 'assets/monuments/grand-buddha.png' },
  { id: 'temple-or', name: 'Temple d\'or d\'Amritsar', image: 'assets/monuments/temple-or.png' },
  { id: 'qutub-minar', name: 'Qutub Minar', image: 'assets/monuments/qutub-minar.png' },
  { id: 'hawa-mahal', name: 'Hawa Mahal', image: 'assets/monuments/hawa-mahal.png' },
  { id: 'meenakshi', name: 'Temple Mînâkshî', image: 'assets/monuments/meenakshi.png' },
  { id: 'taj-lake', name: 'Taj Lake Palace', image: 'assets/monuments/taj-lake.png' },
  { id: 'victoria-falls', name: 'Chutes Victoria', image: 'assets/monuments/victoria-falls.png' },
  { id: 'table-mountain', name: 'Table Mountain', image: 'assets/monuments/table-mountain.png' },
  { id: 'mosquee-hassan', name: 'Mosquée Hassan II', image: 'assets/monuments/mosquee-hassan.png' },
  { id: 'djemaa-el-fna', name: 'Djemaa el-Fna', image: 'assets/monuments/djemaa-el-fna.png' },
  { id: 'saint-marc', name: 'Place Saint-Marc', image: 'assets/monuments/saint-marc.png' },
  { id: 'doge-venise', name: 'Palais des Doges', image: 'assets/monuments/doge-venise.png' },
  { id: 'neuschwanstein-bavaria', name: 'Neuschwanstein', image: W + '/a/ae/Castle_Neuschwanstein.jpg/640px-Castle_Neuschwanstein.jpg' },
  { id: 'chateau-versailles', name: 'Château de Versailles', image: 'assets/monuments/chateau-versailles.png' },
  { id: 'mont-saint-michel', name: 'Mont-Saint-Michel', image: 'assets/monuments/mont-saint-michel.png' },
  { id: 'saint-basile-moscow', name: 'Saint-Basile Moscou', image: 'assets/monuments/cathedrale-saint-basile.png' },
  { id: 'wat-arun', name: 'Wat Arun', image: 'assets/monuments/wat-arun.png' },
  { id: 'grand-palace-bangkok', name: 'Grand Palais Bangkok', image: 'assets/monuments/grand-palace-bangkok.png' },
  { id: 'temple-jade', name: 'Temple du Jade', image: 'assets/monuments/temple-jade.png' },
  { id: 'muralla-china', name: 'Grande Muraille', image: W + '/f/fa/Great_Wall_of_China_July_2006.JPG/640px-Great_Wall_of_China_July_2006.JPG' },
  { id: 'forbidden-beijing', name: 'Cité interdite Pékin', image: 'assets/monuments/forbidden-city.png' },
  { id: 'temple-heaven', name: 'Temple du Ciel', image: 'assets/monuments/temple-heaven.png' },
  { id: 'summer-palace', name: 'Palais d\'été', image: 'assets/monuments/summer-palace.png' },
  { id: 'fuji', name: 'Mont Fuji', image: 'assets/monuments/fuji.png' },
  { id: 'kinkaku-ji', name: 'Kinkaku-ji', image: 'assets/monuments/kinkaku-ji.png' },
  { id: 'torii-miyajima', name: 'Torii de Miyajima', image: 'assets/monuments/torii-miyajima.png' },
  { id: 'senso-ji', name: 'Senso-ji', image: 'assets/monuments/senso-ji.png' },
  { id: 'hollywood-sign', name: 'Hollywood Sign', image: 'assets/monuments/hollywood-sign.png' },
  { id: 'capitol-washington', name: 'Capitole Washington', image: 'assets/monuments/capitol-washington.png' },
  { id: 'white-house', name: 'Maison Blanche', image: 'assets/monuments/white-house.png' },
  { id: 'washington-monument', name: 'Washington Monument', image: 'assets/monuments/washington-monument.png' },
  { id: 'brooklyn-bridge', name: 'Brooklyn Bridge', image: 'assets/monuments/brooklyn-bridge.png' },
  { id: 'willis-tower', name: 'Willis Tower', image: 'assets/monuments/willis-tower.png' },
  { id: 'statue-unity', name: 'Statue de l\'Unité', image: 'assets/monuments/statue-unity.png' },
  { id: 'marina-bay', name: 'Marina Bay Sands', image: 'assets/monuments/marina-bay.png' },
  { id: 'petronas', name: 'Tours Petronas', image: 'assets/monuments/petronas.png' },
  { id: 'tokyo-tower', name: 'Tour de Tokyo', image: 'assets/monuments/tokyo-tower.png' },
  { id: 'skytree', name: 'Tokyo Skytree', image: 'assets/monuments/skytree.png' },
  { id: 'oriental-pearl', name: 'Perle orientale', image: 'assets/monuments/oriental-pearl.png' },
  { id: 'tower-bridge-london', name: 'Tower Bridge Londres', image: 'assets/monuments/tower-bridge.png' },
  { id: 'millau-viaduc', name: 'Viaduc de Millau', image: 'assets/monuments/millau-viaduc.png' },
  { id: 'guggenheim-bilbao', name: 'Guggenheim Bilbao', image: 'assets/monuments/guggenheim-bilbao.png' },
  { id: 'padrao-descobrimentos', name: 'Padrão dos Descobrimentos', image: 'assets/monuments/padrao-descobrimentos.png' },
  { id: 'louvre-pyramid', name: 'Pyramide du Louvre', image: 'assets/monuments/louvre-pyramid.png' },
  { id: 'notre-dame-strasbourg', name: 'Cathédrale Strasbourg', image: 'assets/monuments/notre-dame-strasbourg.png' },
  { id: 'palace-westminster', name: 'Westminster', image: 'assets/monuments/palais-westminster.png' },
  { id: 'colosseum', name: 'Colisée', image: W + '/5/53/Colosseum_in_Rome%2C_Italy_-_April_2007.jpg/640px-Colosseum_in_Rome%2C_Italy_-_April_2007.jpg' },
  { id: 'trevi', name: 'Trevi', image: 'assets/monuments/fontana-trevi.png' },
  { id: 'eiffel', name: 'Tour Eiffel Paris', image: W + '/a/a8/Tour_Eiffel_Wikimedia_Commons.jpg/640px-Tour_Eiffel_Wikimedia_Commons.jpg' },
  { id: 'liberty', name: 'Statue de la Liberté NY', image: W + '/d/d3/Statue_of_Liberty%2C_NY.jpg/640px-Statue_of_Liberty%2C_NY.jpg' },
  { id: 'taj', name: 'Taj Mahal Inde', image: W + '/1/15/Taj_Mahal.jpg/640px-Taj_Mahal.jpg' },
  { id: 'great-wall', name: 'Grande Muraille Chine', image: W + '/f/fa/Great_Wall_of_China_July_2006.JPG/640px-Great_Wall_of_China_July_2006.JPG' },
  { id: 'burj', name: 'Burj Khalifa Dubaï', image: 'assets/monuments/burj-khalifa.png' },
  { id: 'parthenon-athens', name: 'Parthénon Athènes', image: W + '/8/8f/Parthenon_from_south.jpg/640px-Parthenon_from_south.jpg' },
  { id: 'stonehenge-uk', name: 'Stonehenge Angleterre', image: 'assets/monuments/stonehenge.png' },
  { id: 'lincoln-dc', name: 'Lincoln Memorial DC', image: 'assets/monuments/lincoln-memorial.png' },
  { id: 'blue-mosque', name: 'Mosquée Bleue Istanbul', image: 'assets/monuments/mosquee-bleue.png' },
  { id: 'saint-peter', name: 'Saint-Pierre Vatican', image: 'assets/monuments/basilique-saint-pierre.png' }
];
